### ISSUE TITLE
Can't fetch NZX quotes via NZX (or any alternative)

### ISSUE THREAD

**Issue by ksdhans** [finance-quote/finance-quote#100]
It currently isn't possible to get quotes from the NZ stock exchange. It used to be possible to get it via the Yahoo NZ option, until Yahoo shut it down. Now all methods, including NZX.pm fail. 

It would be great if we had a usable option again.

**Comment by goodvibes2** [comment]
I think Yahoo_JSON and AlphaVantage will probably work for most NZ stocks.
To use AlphaVantage, you will have to get a free key, and if you have many stocks, you may have to either wait for F::Q 1.48 to be released or manually get the latest Quote.pm and AlphaVantage.pm from this github website. If you cannot get it to work, please advise an example stock code and approximate price. Are you using GnuCash or some other app?

**Comment by goodvibes2** [comment]
yahoo_json seems to work.

C:\Program Files (x86)\gnucash\bin>perl gnc-fq-dump -v yahoo_json MEL.NZ
Finance::Quote fields Gnucash uses:
    symbol: MEL.NZ               <=== required
      date: 09/24/2018           <=== recommended
  currency: NZD                  <=== required
      last: 3.365                <=\
       nav:                      <=== one of these
     price:                      <=/
  timezone:                      <=== optional

All fields returned by Finance::Quote for stock MEL.NZ

stock           field  value
-----           -----  -----
MEL.NZ       currency: NZD
MEL.NZ           date: 09/24/2018
MEL.NZ      div_yield: 4.268657
MEL.NZ            eps: 0.078
MEL.NZ       exchange: Sourced from Yahoo Finance (as JSON)
MEL.NZ        isodate: 2018-09-24
MEL.NZ           last: 3.365
MEL.NZ         method: yahoo_json
MEL.NZ           name: MEL.NZ (MERIDIAN ENERGY LT NPV)
MEL.NZ             pe: 43.141026
MEL.NZ        success: 1
MEL.NZ         symbol: MEL.NZ
MEL.NZ           type: EQUITY
MEL.NZ         volume: 103499
MEL.NZ     year_range:        2.745 - 3.415

In GnuCash Security Editor, you need to set:
Symbol/abreviation: MEL.NZ
Type of quote source: Single, Yahoo as JSON

AlphaVantage doesn't seem to work. I don't know what suffix they expect for the NZX. I tried NZ, NZX, NX.

**Comment by ksdhans** [comment]
It looks like I have a broken installation, because that doesn't work either. Wireshark says it was looking up download.finance.yahoo.com, which doesn't exist, and I found old versions of Finance::Quote. Deleting the old versions didn't help, though. Will do a reinstall later...

**Comment by ksdhans** [comment]
What version of Finance::Quote are you testing this with? I've now got Finance::Quote v1.47, and GnuCash 3.1, and it's still failing with the settings you gave.

**Comment by goodvibes2** [comment]
I've got Finance::Quote 1.47 with latest Quote.pm and AlphaVantage.pm from https://github.com/finance-quote/finance-quote
and yahoo_JSON.pm from https://github.com/goodvibes2/finance-quote.
I'm surprised the unmodified 1.47 doesn't work for you.
Does the 'perl gnc-fq-dump -v yahoo_json MEL.NZ' command work for you? If not, is there an error message?
Or does gnc-fq-dump work and only GnuCash that is failing?
You may need my (goodvibes2) yahoo_JSON.pm mod if you have many stocks as I found that the many warnings seems to make GnuCash fail.
Also, if you have multiple currencies, you will need an AlphaVantage key as all currency lookups are now done via AlphaVantage.
See https://wiki.gnucash.org/wiki/FAQ#Q:_Why_doesn.27t_online_quoting_work.3F

**Comment by ksdhans** [comment]
With v1.47, 'perl gnc-fq-dump -v yahoo_json MEL.NZ' gives me:
Finance::Quote fields Gnucash uses:
    symbol: MEL.NZ               <=== required
      date: 00/00/2000           <=== recommended
  currency: NZD                  <=== required
      last: 3.37                 <=\
       nav:                      <=== one of these
     price:                      <=/
  timezone:                      <=== optional

All fields returned by Finance::Quote for stock MEL.NZ

stock           field  value
-----           -----  -----
MEL.NZ       currency: NZD
MEL.NZ           date: 00/00/2000
MEL.NZ       exchange: Sourced from Yahoo Finance (as JSON)
MEL.NZ        isodate: 2000-00-00
MEL.NZ           last: 3.37
MEL.NZ         method: yahoo_json
MEL.NZ           name: MEL.NZ (MERIDIAN ENERGY LT NPV)
MEL.NZ        success: 1
MEL.NZ         symbol: MEL.NZ
MEL.NZ           type: EQUITY
MEL.NZ         volume: 1817392

The one problem I see is the invalid date.

**Comment by goodvibes2** [comment]
That's one of the things my mods fix, but it doesn't stop Gnucash from using the price. It just means Gnucash uses the current date. Note: From memory, you'll also need to use my Quote.pm to fix the date problem, but that will then not contain the code to limit the no of currency queries AlphaVantage needs.

**Comment by ksdhans** [comment]
I've tried using your Quote.pm, and I'm still getting the invalid dates. 

GnuCash managed to get one quote when I disabled all the other stocks. It's failing after adding the others back in. It's also intermittently failing with an "Unknown error," which makes even less sense.

**Comment by ksdhans** [comment]
Yes, I was using your yahoo_JSON.pm and I have an AlphaVantage Key.

I've tried reinstalling, but it fails with:
Warning: Cannot install Date::Manip, don't know what it is.

**Comment by ksdhans** [comment]
I installed it using the "Install Online Price Retrieval" (there's nothing in the GnuCash Windows menu for this). Actually, I downloaded Strawberry Perl separately, because the script downloads v5.18 (from 2014). 

Executing "cpan install Finance::Quote" didn't work. However, "cpan install Date::Manip::Base" did. So it's working now. 

I'm not sure which module(s) need fixing for this. Why doesn't "cpan install Date::Manip" work any more? Is it even supposed to work? Or, does GnuCash's installer script need fixing?

**Comment by goodvibes2** [comment]
"cpan install Date::Manip" used to work so it is probably not working due to the later version of perl you manually installed. You should raise a GnuCash bug about that, and let them know what version of perl you installed.
I see that the version of perl installed by the soon to be released GnuCash 3.3, will be 5.28, see https://github.com/Gnucash/gnucash-on-windows/commit/81ab3b35 for bug https://bugs.gnucash.org/show_bug.cgi?id=791725, so your work-around of installing Date::Manip::Base could be very helpful.

**Comment by ksdhans** [comment]
Okay, I've created a bug ticket there: https://bugs.gnucash.org/show_bug.cgi?id=796873

I'm closing this ticket because Finance::Quote itself is working fine.
