### ISSUE TITLE
Add ECB reference rates as source

### ISSUE THREAD

**Issue by frakturfreak** [finance-quote/finance-quote#102]
Could you please add a parser for the daily Euro reference rates provided by the European Central Bank:

https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html

For reasoning why do so, I’ll quote the ECB because I’ve got nothing to add:

““Given that the ECB reference rates are provided as a public good for individual citizens and institutions, it is essential to safeguard a high level of integrity and to underline that they are intended to be used solely as a reference for information rather than when making transactions,” said ECB Executive Board member Benoît Cœuré.

The ECB has been setting and publishing its reference rates for the euro on a daily basis since the currency was launched in January 1999. These rates are often used for the annual financial statements of corporations, tax returns, statistical reports and economic analyses. They are the most accessed item on the ECB’s website, with more than a million visits per month.“

So they might not be used for the real transactions but are used as a important reporting measure.

**Comment by vincentl** [comment]
Added support for ECB in merge 6e814cc0730eb0979d6dbb944fbf711869d1cf50.
