### ISSUE TITLE
Add Morningstar AU source for managed funds

### ISSUE THREAD

**Issue by jalonavens** [finance-quote/finance-quote#112]
The [Morningstar AU](https://www.morningstar.com.au/) website has a comprehensive quotation service for Australian managed funds. While there there is a Finance::Quote::Morningstar module for the [Morningstar SW](https://morningstar.se/) website and Finance::Quote::MStarUK for the [Morningstar UK](morningstar.co.uk ) website there is none for the Australian variant.

As such I've written a `Finance::Quote::MorningstarAU` module to extract quotes based on the fund's APIR code via 2 new `morningstarau` and `aufunds` methods. Have even written the `.t` test suites for both these methods :-).

How can I add these to the project?

This should also help out with a source of Australian managed fund quotes issue as raised in #91.

**Comment by bpschuck** [comment]
Create a fork of Finance-Quote, optionally create a branch in that fork for your changes/additions. Then create a pull request here on the official F-Q repository.
[Creating a pull request](https://help.github.com/en/articles/creating-a-pull-request)
As time allows one of the contributors with write access will review and possibly merge your changes into the master branch. 
After that I am unclear on the process to upload it to CPAN, mostly whether or not it should always be the same author.

**Comment by jalonavens** [comment]
Okay @bpschuck have done as you've specified into pull request #113. Please excuse any github or Perl errors - first time using github and a bit rusty with Perl!

**Comment by ecocode** [comment]
this has been merged.  Thanks for your work !
