### ISSUE TITLE
Fund Library, CA scraper not working

### ISSUE THREAD

**Issue by DoughMucker** [finance-quote/finance-quote#114]
Hello, 
Some time after May 16, 2019, the date of my last price update, the "Fund Library, CA" scraper in F::Q stopped working. I suspect fundlibrary.com has changed their website. Other quotes are still working as expected through Alpha Vantage. None of the other Canadian mutual fund scrapers (BMO Nesbitt Burns, Canada 
Mutual, Finance Canada, TD Waterhouse Funds) seem to be working either, even after searching the gnucash mail list archives for methods people have used in the past.

When trying to get my quotes, I see:
"Unable to retrieve quotes for these items:
FUND: xxxxx
FUND: yyyyy
FUND: zzzzz
Continue using only the good quotes?"

As expected, selecting "No" will cancel and selecting "Yes" will update the other stock prices.

If any logs will help, let me know and I will post them.

Thanks,
Doug

**Comment by bpschuck** [comment]
Names and symbols for funds that were getting quotes before 05/16/2019 would be helpful.
But you are likely correct in that Fund Library has changed their website. I've been poking around their site and its related fundata.com looking for information on APIs and tools with no success.

**Comment by DoughMucker** [comment]
NBC887 (National Bank Canadian Equity Growth Fund) was previously working. Another, TDB970 (TD Balanced Growth) was previously working but doesn't now; but some caution, TDB970 will change to TDB3533 on June 14. Could give you some more TDB symbols but they will also be changing.

**Comment by bpschuck** [comment]
From what I've found, the URL to fetch would look something like [https://www.fundlibrary.com/MutualFunds/GetFundSearchResults?searchText=NBC887&cifscCategoryId=0&fundCompanyId=0&fundTypeId=0&isGradeA=true&isGradeB=true&isGradeC=true&isGradeD=true&isGradeE=true&sortBy=Default&page=0](https://www.fundlibrary.com/MutualFunds/GetFundSearchResults?searchText=NBC887&cifscCategoryId=0&fundCompanyId=0&fundTypeId=0&isGradeA=true&isGradeB=true&isGradeC=true&isGradeD=true&isGradeE=true&sortBy=Default&page=0). Probably going to take a bit of time before someone volunteers to rewrite the module.

**Comment by patherror** [comment]
How do I get this fixed program into my computer

**Comment by bpschuck** [comment]
@DoughMucker, Happy Thanksgiving if you celebrated it. Could you please supply a couple symbols to be used in the module's test file. Thanks!

**Comment by DoughMucker** [comment]
> @DoughMucker, Happy Thanksgiving if you celebrated it. Could you please supply a couple symbols to be used in the module's test file. Thanks!

Cheers!
NBC887
TDB3533
