### ISSUE TITLE
IEX API Change

### ISSUE THREAD

**Issue by knappster1** [finance-quote/finance-quote#116]
I've been using IEX quotes in gnucash for a little under a year without issue.  They just changed their API so it is no longer working.
https://iextrading.com/developer/docs/#getting-started

This is the information that I used to setup IEX initially:
https://github.com/finance-quote/finance-quote/issues/97

Alphavantage is still a problem for me in gnucash presumably because it makes too many consecutive calls.  I have the API key for IEX now.  Is there any way to use it with finance::quote?

**Comment by vincentl** [comment]
I didn’t realize there was a separate Perl module just for IEX support and recently add support with commit 02298dd.  

For the new https://iexcloud.io/ site, we need to make a decision about API keys.  

Different environment variables for each service?  Then GNUCash needs to add a preference for each service.

A universal environment variable with comma separated SERVICE:APIKEY TOKENS?

**Comment by vincentl** [comment]
I sent a message to gnucash-devel mailing list to get opinions on how to expose multiple API keys to client applications.  Once we have a plan, I'm migrate IEXTrading.pm to IEXCloud.pm.

**Comment by knappster1** [comment]
@vincentl, thanks for the quick response.  I would say that I am not in a position to decide on how to handle the api keys, so hopefully the mailing list will be responsive.

Personally, I dont have an issue with multiple environment variables, since they should be able to all have unique names.  I don't know the consequences of either option, though.

I look forward to seeing how this turns out.  I may have some questions about installing from master when the time comes, though...

**Comment by bpschuck** [comment]
@knappster1 and @vincentl - Seems the [Finance::Quote::IEX module](https://www.cpan.org/authors/id/J/JT/JTPALMER/Finance-Quote-IEX-0.001001.readme) was created and uploaded to CPAN outside of this official F::Q project. Looks like knappster1 is perhaps setting FQ_LOAD_QUOTELET, or some other hack to use the IEX module. To avoid ambiguity or stepping on toes, maybe get in contact with its author, Jeffrey Palmer?

WRT API keys, I believe most GnuCash users likely use just one of the quote services that require an API key. Maybe in even rarer cases two or more. So in this case I prefer the KISS (keep it simple simon) method of just specifying them in the local environment file.

**Comment by ecocode** [comment]
Hi,Please note that the current module on the master branch has been updated to conform to alphavantage imposed query limit.--Erik ColsonOn 15 Jun 2019 14:33, knappster1 <notifications@github.com> wrote:
Alphavantage is still a problem for me in gnucash presumably because it makes too many consecutive calls.

**Comment by ecocode** [comment]
Hello Jeffrey,

I'm one of the maintainers of the Perl module Finance::Quote.  Your
module Finance::Quote::IEX has been used by end users for some time and
I thank you for providing this module.

We want to keep this module working and therefor it needs to be updated.
It would be cleaner to include the module into the Finance::Quote
project, so we can keep an eye on it and hopefully keep it functioning
for years to come.

If that is ok for you we will be glad to give you a commit bit to the
Finance::Quote project, so you can update it if needed.

If you agree we will take over the module sources into the project.  You
will need to free the namespace in PAUSE to prevent conflicts.
Eventually we might need to change the name if for some reason conflicts
cannot be solved..

Please let us know your decision which we will, of course, respect.

best
--
erik colson

**Comment by vincentl** [comment]
Pull request #106 added support for IEX with new code based on the AlphaVantage.pm.  With commit 38a70c, I just pushed a migration of that code to pull from IEXCloud.io instead.

For this version, users need to set the environment variable IEXCLOUD_API_KEY after signing up at IEXCloud.io.

So I don't think we need anything to support pulling from IEX, but a review of IEXCloud.pm would be helpful.

**Comment by ecocode** [comment]
Great job @vincentl !

**Comment by ecocode** [comment]
Hi Erik,

I'm fine with moving Finance::Quote::IEX into Finance::Quote.  It sounds
like that would be the best for everyone if other people are using it now
and there's interest.

Let me know what changes to make in PAUSE and if there's anything else
I can help with.

Thanks,
Jeff

**Comment by vincentl** [comment]
Since the IEXCloud.pm is working, I don't think we need anything from Jeff so I'm closing this issue.

**Comment by knappster1** [comment]
Thanks for the help.  I look forward to seeing the 1.48 release.  In the meantime, I've managed to modify the IEX.pm file to update the URL and key information.
