### ISSUE TITLE
1.48 and 1.49 dists contain BerkeleyDB files

### ISSUE THREAD

**Issue by pghmcfc** [finance-quote/finance-quote#123]
Don't think these should be there:
```
-rw-r--r-- ec/ec         16384 2019-06-30 11:21 Finance-Quote-1.49/lib/GPATH
-rw-r--r-- ec/ec         16384 2019-06-30 11:21 Finance-Quote-1.49/lib/GTAGS
-rw-r--r-- ec/ec         16384 2019-06-30 11:21 Finance-Quote-1.49/lib/GRTAGS
```
They get installed on to the user's system too.

**Comment by ecocode** [comment]
Paul Howarth <notifications@github.com> writes:

> Don't think these should be there:
> ```
> -rw-r--r-- ec/ec         16384 2019-06-30 11:21 Finance-Quote-1.49/lib/GPATH
> -rw-r--r-- ec/ec         16384 2019-06-30 11:21 Finance-Quote-1.49/lib/GTAGS
> -rw-r--r-- ec/ec         16384 2019-06-30 11:21 Finance-Quote-1.49/lib/GRTAGS
> ```
> They get installed on to the user's system too.

Thanks for mentioning.  They won't appear in future releases anymore.

best
--
erik colson
