### ISSUE TITLE
Alphavantage "close" value is not compliant

### ISSUE THREAD

**Issue by qzwongo** [finance-quote/finance-quote#129]
Per F::Q documentation, section Labels, "close" is defined as  "Previous Close".  The alphavantage module returns the provided "last" value for both "close" and "last".  

While not an issue for those building a table of daily values, it does not allow accurate calculation of daily change.  

Data fetched from Alphavantage includes the last 100 days.  It should be a straightforward task to find the "last" value from the previous trading day's entry and use that for the returned "close" value.  From that, the "p_change" value could also be easily calculated.

**Comment by bpschuck** [comment]
While you are technically correct, remember that the AlphaVantage module was a quick replacement for when the non-json Yahoo module no longer worked after Yahoo no longer offered the API it used. Any reason why you don't use yahoo_json instead of AlphaVantage?

**Comment by bpschuck** [comment]
Doing a little research. I don't think the [Quote Endpoint API](https://www.alphavantage.co/documentation/#latestprice) was available when AlphaVantage.pm was first written. It returns the following JSON:

`{
    "Global Quote": {
        "01. symbol": "MSFT",
        "02. open": "152.1000",
        "03. high": "152.3000",
        "04. low": "151.2800",
        "05. price": "151.3800",
        "06. volume": "11977300",
        "07. latest trading day": "2019-11-29",
        "08. previous close": "152.3200",
        "09. change": "-0.9400",
        "10. change percent": "-0.6171%"
    }
}`

It may be worth the effort to rewrite the module to use this API. It would address this issue, and supply more information.

**Comment by qzwongo** [comment]
Thanks for your feedback @bpschuck.  

I wasn't using the yahoo_json interface because I like waiting an extra minute for every 5 quotes!  Somehow i followed the alphavantage track until it became quite stable and reliable, if slow, and meanwhile missed the advent of yahoo_json.  I shall endeavor to remedy my mistake.

Agreed the Quote Endpoint API appears a much improved solution for the alphavantage module compared to my suggestion.  Not sure if that's new since I posted in July.  If not, I overlooked it as a way both to provide the requested data (without calculation) and to greatly reduce traffic from their site.

Cheers

**Comment by bpschuck** [comment]
On 12/1/19 11:24 AM, qzwongo wrote:

> I wasn't using the yahoo_json interface because I like waiting an
> extra minute for every 5 quotes! Somehow i followed the alphavantage
> track until it became quite stable and reliable, if slow, and
> meanwhile missed the advent of yahoo_json. I shall endeavor to remedy
> my mistake.

I am curious if using yahoo_json addresses your needs. If I were to
guess, you're using F::Q outside of GnuCash?

> Agreed the Quote Endpoint API appears a much improved solution for
> the alphavantage module compared to my suggestion. Not sure if that's
> new since I posted in July. If not, I overlooked it as a way both to
> provide the requested data (without calculation) and to greatly
> reduce traffic from their site.
If I recall, a few of the AlphaVantage APIs currently available did not
exist some months ago. In the next few weeks I may tackle a couple of
the issues posted since July, and changing the AlphaVantage module to
utilize the Quote Endpoint API instead of the Daily Time Series.

Thank you for your response.

- Bruce S.

**Comment by bpschuck** [comment]
This issue is addressed after merging #131 .
