### ISSUE TITLE
SourceForge Finance::Quote Web-page Correction Needed

### ISSUE THREAD

**Issue by jeixav** [finance-quote/finance-quote#13]
On SourceForge, the Finance::Quote Git repository address is given as: http://github.com/pfenwick/finance-quote. I think this should be changed to: https://github.com/pjf/finance-quote.

The SourceForge page in question is: http://finance-quote.sourceforge.net/developer.html

**Comment by zmughal** [comment]
Bumping. The link still needs to be corrected. :-D

**Comment by ecocode** [comment]
done... although the correct link is https://github.com/finance-quote/finance-quote
