### ISSUE TITLE
IEXCloud.pm throws exception during trading hours

### ISSUE THREAD

**Issue by vincentl** [finance-quote/finance-quote#134]
latestTime is not always part of the response, which causes an exception.

Propose using latestUpdate instead.

API documented at https://iexcloud.io/docs/api/

**Comment by bpschuck** [comment]
Not sure how quickly, if at all, Erik may respond. Using latestUpdate is probably the best way to correct the exception issue.

**Comment by vincentl** [comment]
Just wanted someone else to sanity check the plan.  I'll implement and push the change soon.

**Comment by ecocode** [comment]
yep.  latestUpdate it should be...  Thx for your awesome work and wish you and Bruce a happy new year !

**Comment by vincentl** [comment]
Fixed in 6acf0fcbbc7a8515a2481e326cf0eb5fb40fe609
