### ISSUE TITLE
Bourso module not working

### ISSUE THREAD

**Issue by jmpacquet** [finance-quote/finance-quote#139]
Since I had a need for it, please find here the patch I use. To check it, the symbol for BNP PARIBAS  on Paris Stock Exchange is 1rPBNP. You can compare the result with Yahoo Finance where the symbol for BNP PARIBAS on Paris Stock Exchange is BNP.Pa.
gnc-fq-dump -v bourso 1rPBNP
gnc-fq-dump -v yahoo_json BNP.Pa

[Bourso.zip](https://github.com/finance-quote/finance-quote/files/4398981/Bourso.zip)

**Comment by bpschuck** [comment]
Are you not comfortable enough with Git/Github to create a pull request? No big deal if you would rather not, just asking. Otherwise myself or another maintainer will look at this.
Thank you.

**Comment by jmpacquet** [comment]
No, I'm not familiar with Git/Github: I've used cvs and svn before, but I'm willing to learn. I'll try.

**Comment by bpschuck** [comment]
As I said, not to worry. I'll take this on. Thanks for your contribution.
The current module used these symbols for testing:
"FR0000441677",    # Fund
"AF",              # Stock, EUR, Nyse Euronext
"MSFT",            # Stock, USD, NASDAQ
"SOLB",            # Stock, EUR, BRUXELLES
"CNP",             # Stock, EUR, Nyse Euronext
"FR0010371401",    # Bond
"FR0012773687",    # Warrant
"FR0003500008",    # Index
"LU0207947044",    # Bond

Perhaps you can confirm if these should work, and supply a couple more symbols in addition to "1rPBNP"?

Again, thanks!

**Comment by jmpacquet** [comment]
FR0000441677 works as is, AF symbol is 1rPAF (Euronext Paris), MSFT as is, SOLB symbol is FF11-SOLB for Euronext Brussels and 1rPSOLB for Paris, CNP symbol is 1rPCNP. Of the last 4 isin only FR0012773687 does not work as is (it's probably non existing!).
I managed to create a pull request...

**Comment by bpschuck** [comment]
I see your pull request. For your pull request to be merged, you will need to get the test script t/bourso.t to execute properly, and update the Modules-README.yml file (see completed sections of it for syntax and information). Thank you.

**Comment by jmpacquet** [comment]
t/bourso.t now executes properly and Modules-README.yml has been updated. Bourso.pm also got some updates.

**Comment by vincentl** [comment]
Merge 886cb352ee450a3079f7e5dfe3b84d781b5f8b85 closes this issue.

**Comment by bpschuck** [comment]
@jmpacquet - I am wondering why you removed `europe` and `france` from the method hash in commit [e26484b](https://github.com/finance-quote/finance-quote/commit/e26484b3712d3332d50f6e5e581829344b6e313e) so Bourso is no longer used as a failover method for those?

**Comment by jmpacquet** [comment]
I removed europe because bourso:

1. does not cover all europe  (north europe is only partly covered: many 
norvegian and swedish stocks are missing)

2. does cover more than europe: you get NYSE, NASDAQ and most Canadian 
stocks.

It was probably a mistake to remove france because france is very well 
covered.

-- 

jmp
