### ISSUE TITLE
Unable to build Finance Quote on MacOS 10.15.4

### ISSUE THREAD

**Issue by IVIDR** [finance-quote/finance-quote#141]
I am trying to build finance quote on a MacOS 10.15.4 computer but the install is failing.
Xcode and developer tools are installed on this system
perl version is base OSX perl 5, version 18, subversion 4 (v5.18.4)

When installing the following warnings and errors are listed from terminal

...
Warning: prerequisite DateTime::Format::Strptime 0 not found.
Warning: prerequisite JSON::Parse 0 not found.
Generating a Unix-style Makefile
Writing Makefile for Finance::Quote
Writing MYMETA.yml and MYMETA.json
---- Unsatisfied dependencies detected during ----
----     ECOCODE/Finance-Quote-1.49.tar.gz    ----
    JSON::Parse [requires]
    DateTime::Format::Strptime [requires]
Running make test
  Delayed until after prerequisites
Running make install
  Delayed until after prerequisites
Running install for module 'JSON::Parse'
...

Json3.xs:1:10: fatal error: 'EXTERN.h' file not found
#include "EXTERN.h"
         ^~~~~~~~~~
1 error generated.
make: *** [Json3.o] Error 1
  BKB/JSON-Parse-0.56.tar.gz
  /usr/bin/make -- NOT OK
'YAML' not installed, will not store persistent state

and many other errors follow. 
Per the installation directions, the Developer Tools and Xcode should be sufficient to build finance quote. Are there other packages that i will also need to install to before 
sudo /Applications/Gnucash.app/Contents/Resources/bin/gnc-fq-update
can be properly compiled?

Thanks for any suggestions or help.

**Comment by bpschuck** [comment]
You may need install the SDK headers package (see
https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes#3035624).

On Mojave (10.14.x) that was:
sudo installer -pkg
/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg

May be different for Catalina.

Hope this helps.

**Comment by bpschuck** [comment]
I should add, that this is an issue with the build environment (OSX 10.15/Catalina) and not with the Finance::Quote source.
So unless there are objections from other maintainers, I am going to close this issue in a few days.
