### ISSUE TITLE
TSP.pm needs to be updated to work with new site

### ISSUE THREAD

**Issue by jhaiduce** [finance-quote/finance-quote#148]
The TSP module is designed to parse an HTML table on the TSP.gov site. However, the site has been redesigned and there is no longer an HTML table available to parse.

The original site looked like this: https://web.archive.org/web/20200614150224/https://www.tsp.gov/InvestmentFunds/FundPerformance/index.html

The new site (https://www.tsp.gov/fund-performance/share-price-history/) replaces the HTML table with a div that is replaced with a table using client-side JavaScript. The client side script generates the table from CSV data that is fetched from https://secure.tsp.gov/components/CORS/getSharePricesRaw.html.

TSP.pm needs to be changed to parse this CSV data now that the HTML table no longer exists.

**Comment by vincentl** [comment]
Thanks for investigating.  This should be straight forward to address.  Will post a follow-up soon.

**Comment by vincentl** [comment]
Fixed with commit dcf3d8
