### ISSUE TITLE
Modules for removal

### ISSUE THREAD

**Issue by AbstractMethod** [finance-quote/finance-quote#152]
FinanceCanada.pm (financecanada) and StockHouseCanada.pm (stockhousecanada_fund) sites are both permanently down.

In the latter's case, there is a stockhouse.com but the site has completely changed, and is no longer Canada centric in any event, so there would need to be a new module.

**Comment by vincentl** [comment]
Thanks for investigating these two modules.  Removed in commits bcc5562f13bb9a522c35ababe2459c1688f80b32 and b22963e664a6455ef83620cf05f875bf4a65ea3a.
