### ISSUE TITLE
Currency plan & API Keys

### ISSUE THREAD

**Issue by vincentl** [finance-quote/finance-quote#168]
Issue #65, #102, & #126 reference Currency.

Currently, Finance::Quote does something that depends on AlphaVantage.

Should/can Finance::Quote support multiple Currency backend modules?
How should API keys (Fixer.io if we add it, AlphaVantage) be handled with respect to the new module-specific arguments to new()?

**Comment by bpschuck** [comment]
Vincent,

WRT Currencies:

I believe for the greater community of users, forcing them to get an API 
key from AlphaVantage even though they are not getting security and fund 
quotes from AV is a bit cumbersome. Unless of course we cannot locate a 
source for this information that does not require a key or other access 
credentials.

As for multiple API keys, I'm still a fan of simply listing them in the 
Gnucash environment file. I've been doing some testing with WorldTrading 
and QUANDL and have the keys in my bashrc and 
/Applications/Gnucash.app/Contents/Resources/etc/gnucash/environment on 
my Mac. Yeah, would be nice if they can be defined in GnuCash itself, 
but that would coordination with the GnuCash development team.

- Bruce S.

**Comment by vincentl** [comment]
Added Finance::Quote::CurrencyRates modules to support multiple currency rate backends in merge 6e814cc0730eb0979d6dbb944fbf711869d1cf50.  Documented in Quote.pm and Hackers Guide.
