### ISSUE TITLE
Finance Quote 1.50 RC1 - Issue with Currency & Quote.pm file.

### ISSUE THREAD

**Issue by ThierryLes** [finance-quote/finance-quote#173]
Hi,
After some testing on F::Q 1.50 RC1, I come through this bug, while i try to get currency.
(I only test it through Gnucash, as i didn't manage to pass my Alaphavantage key, through the cmd mode, with gnc-fq-dump).
(I use Win 10, GnuCash 4.4 & perl v5.32 and i add to update couple of module: HTML::TokeParser / Spreadsheet::XLSX / Web::Scraper / HTML::TokeParser::Simple)

So when I test the currency module, i get the error message :
**_Unable to retrieve quotes for these items:
 CURRENCY:CHF
 CURRENCY:USD
 CURRENCY:GBP
 CURRENCY:NOK
Continue using only the good quotes?_**

So I did a bit of troubleshooting, using files from Ver 1.49, that i know was working.
I try multiple combination of files **_Currencies.pm_**, **_AlphaVantage.pm_** & **_Quote.pm_** from Ver 1.50RC1 & Ver 1.49,
and with **_Quote.pm_** from Ver 1.49 & **_Currencies.pm_**, **_AlphaVantage.pm_** from Ver 1.50RC1, it managed to solve the problem: No more error & the proper exchange rates were updated in GnuCash with proper date.
My understanding of perl is not good enough to find the solution, So hope some of you can help.

Thierry

**Comment by vincentl** [comment]
It looks like we broke the API that Gnucash was expecting for currency information.  The FinanceQuote currency tests pass, but gnc-fq-dump is showing a perl hash reference for the symbol.  Need to dig into this issue more.

**Comment by AbstractMethod** [comment]
I've done some digging -- Quote.pm has change extensively since Ver 1.49, but from what I found:

Running a simple test from gnc-fq-dump gives no response.

    gnc-fq-dump currency USD CAD
    1 USD = <unknown> CAD

Quote::currency() loops through all the currency rate methods that are defined.  Unfortunately 
```(@{$this->{currency_rate_method}})``` is an empty array.  This array should be defined in the ```new``` method, as such:

    # Load the currency rate methods
    my %currency_check = map { $_ => 1 } @CURRENCY_RATES_MODULES;
    $this->{currency_rate_method} = [];
    foreach my $method (@{$this->{currency_rates}->{order}}) {
        unless (defined($currency_check{$method})) {
          carp "Unknown curreny rates method: $method";
          return;
        }

      my $method_path = "${class}::CurrencyRates::${method}";
      eval {
        autoload $method_path;
        my $args = exists $this->{currency_rates}->{lc($method)} ? $this->{currency_rates}->{lc($method)} : {};
        my $rate = $method_path->new($args);
        die unless defined $rate;
      
        push(@{$this->{currency_rate_method}}, $rate);
      };

      if ($@) {
        next;
      }
    }

From the perl debugger it's hitting the ```die unless defined $rate``` code, so something is wrong with either ```$args``` or ```$method_path```, although the latter looks OK to me.

**Comment by rdorsch** [comment]
currency lookup in general seems to be broken, independent of gnucash:

rd@h370:/usr/share/doc/libfinance-quote-perl/examples$ ./currency-lookup.pl USD AUD
Urgh!  Nothing back
rd@h370:/usr/share/doc/libfinance-quote-perl/examples$

**Comment by vincentl** [comment]
We were experimenting with how to support more sources that require an API key.  If you change currency-lookup.pl to:

`my $q = Finance::Quote->new(currency_rates => {
                              order => ['AlphaVantage'],
                              'alphavantage' => {API_KEY => 'YOUR-API-KEY'}
                              }
                            });

`
it should work.

I thought we kept the hook in for the ALPHAVANTAGE_API_KEY environment variable.

What does running gnc-fq-dump with the environment variable ALPHAVANTAGE_API_KEY do?

**Comment by rdorsch** [comment]
What you propose works well in the currency-lookup.pl script (./currency-lookup.pl is the original version, ~/tmp.nobackup/currency-lookup.pl has the modification you posted), but not with gnc-fq-dump and gnc-fq-helper:

```
rd@h370:/usr/share/doc/libfinance-quote-perl/examples$ ./currency-lookup.pl USD EUR
Urgh!  Nothing back
rd@h370:/usr/share/doc/libfinance-quote-perl/examples$ ~/tmp.nobackup/currency-lookup.pl USD EUR
USD->EUR = 0.8399
rd@h370:/usr/share/doc/libfinance-quote-perl/examples$ export ALPHAVANTAGE_API_KEY=<MY_KEY>
rd@h370:/usr/share/doc/libfinance-quote-perl/examples$ ./stockdump.pl AlphaVantage MSFT
$VAR1 = {
          'MSFTnet' => '-4.2100',
          'MSFTcurrency' => 'USD',
          'MSFTlast' => '227.3900',
          'MSFTvolume' => '35267440',
          'MSFTsymbol' => 'MSFT',
          'MSFTdate' => '03/08/2021',
          'MSFTisodate' => '2021-03-08',
          'MSFTclose' => '231.6000',
          'MSFTopen' => '231.3700',
          'MSFTmethod' => 'alphavantage',
          'MSFTsuccess' => 1,
          'MSFTlow' => '227.1300',
          'MSFThigh' => '233.3650',
          'MSFTp_change' => '-1.8178',
          'MSFTcurrency_set_by_fq' => 1
        };
rd@h370:/usr/share/doc/libfinance-quote-perl/examples$ gnc-fq-dump currency USD EUR
1 USD = <unknown> EUR
rd@h370:/usr/share/doc/libfinance-quote-perl/examples$  echo '(currency "USD" "EUR")' | gnc-fq-helper
(#f)
rd@h370:/usr/share/doc/libfinance-quote-perl/examples$
```

Do you know how stockdump.pl makes use of the environment variable ALPHAVANTAGE_API_KEY and why currency-lookup.pl is different?

**Comment by vincentl** [comment]
The plan was to detect ALPHAVANTAGE_API_KEY from the environment in the currency module just like in the quote module, but I missed that.

The plan is for other currency sources, such as Fixer.pm, FinanceQuote is only going to support API keys programmatically, and not via the environment.  We'll keep ALPHAVANTAGE_API_KEY for backwards compatibility.

Once 1.50 is finally release, maybe GnuCash could introduce a way to manage multiple API keys to gain access to these other sources.

I'll try to fix ALPHAVANTAGE_API_KEY in the currency module and make a new release candidate for testing.

**Comment by rdorsch** [comment]
Many thanks. 1.50rc1 is already in Debian experimental (mainly due to this issue). It would be nice to get 1.50 or 1.50rc2 into Debian bullseye (next release), since so many issues have been fixed since 1.49

**Comment by vincentl** [comment]
With ALPHAVANTAGE_API_KEY set in the environment, currency-lookup.pl should now work in v1.50-rc.2

**Comment by ThierryLes** [comment]
Run a quick test after downloading your updated files. Seems ok. Thank you.
