### ISSUE TITLE
Finance Quote 1.50 RC1 - Date issue with bourso.pm

### ISSUE THREAD

**Issue by ThierryLes** [finance-quote/finance-quote#174]
Hi,
After some testing on F::Q 1.50 RC1, I come through this bug, while i try to get quotation update, using Boursorama as a source.
(I use Win 10, GnuCash 4.4 & perl v5.32 and i add to update couple of module: HTML::TokeParser / Spreadsheet::XLSX / Web::Scraper / HTML::TokeParser::Simple)
(I tested through cmd mode, with gnc-fq-dump & through gnucash, with same result).

I tested the updated bourso module first through the cmd mode, with gnc-fq-dump, and i get the following :
**_c:\Program Files (x86)\gnucash\bin>perl gnc-fq-dump bourso FR0000120073
Finance::Quote fields Gnucash uses:
    symbol: 1rPAI                <=== required
      date: ** missing **        <=== recommended
  currency: EUR                  <=== required
      last: 132.15               <=\
       nav:                      <=== one of these
     price:                      <=/
  timezone:                      <=== optional_**

**_This quote will have today's date, which might be incorrect.
   GnuCash will use it, but you might prefer that it doesn't._**

Symbol are correct, but it does not get the date. I try with different stocks, from French market or even US, with the same result.
On i try it in GnuCash, it recover the quotation, but the date will be the date of the day you try to recover the quotation, not the last actual day of quotation. 

I run more test, looking for found instead of stock, and strangely it worked:
**_c:\Program Files (x86)\gnucash\bin>perl gnc-fq-dump bourso FR0010069336
Finance::Quote fields Gnucash uses:
   symbol: FR0010069336         <=== required
     date: 02/16/2021           <=== recommended
 currency: EUR                  <=== required
     last: 1 202.19             <=\
      nav:                      <=== one of these
    price:                      <=/
 timezone:                      <=== optional_**

Now, for some strange reason, the date is in UK/US format (MM/DD/AAAA), where, on My PC, the setup is DD/MM/AAAA.
and the source of the HTML files from boursorama website is using AAAA-MM-DD.
Any way, if I try in Gnucash, it worked fine, and the date is in the right format (DD/MM/AAAA).

I did not find a way around on this one, but looking at bourso.pm, i see that its looking for the date by looking for **_tradeDate_** in the class **_data-ist-init_**. On the Boursorama HTML source, i notice there is many use of  **_data-ist-init_** and most of them return the current date for **_tradeDate_**, and are linked to different quotation, only the last occurrence (at the bottom of the page) of  **_data-ist-init_** seems to embed the proper information (Quotation, name & date), with the proper date.
Could the bourso.pm module get fouled while looking for **_tradeDate_** from top to bottom of the page, and just return the 1st occurrence he found, but still understand that it not right as it's not matching the quotation it was looking for ?
Or could it be an issue with date format ?

Thierry

**Comment by vincentl** [comment]
It looks like using the "HISTORIQUE" page is better.  For your example, after a redirect, you land on

https://www.boursorama.com/cours/historique/1rPAI

Thoughts?

**Comment by bpschuck** [comment]
Using curl it seems the page returned isn't consistent. Which is why the module works for FR0010069336 but not for FR0000120073.

**Comment by bpschuck** [comment]
Closed with PR #194.
@ThierryLes - in the meantime for a quick fix, edit your Bourso.pm file. Change $symbol to $stock in the calls to the store_date method.
