### ISSUE TITLE
Finance Quote 1.50 RC1 - HU.pm - Deprecated regex will be fatal in Perl 5.32

### ISSUE THREAD

**Issue by CleanShed** [finance-quote/finance-quote#180]
Finance Quote 1.50 RC1 - HU.pm - Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.32)

Testing FQ release candidate 1.50 generates the following warning due to an unescaped left brace in a regular expression on line 102 of HU.pm.

`Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.32), passed through in regex; marked by <-- HERE in m/window[.]dataSourceResults=({ <-- HERE .+})</script>/ at C:/Utility/Strawberry/perl/site/lib/Finance/Quote/HU.pm line 102.`

Note that this warning occurs regardless of the data source that you use, it is not restricted to Hungarian quotes.

Strawberry Perl v5.30.0 on Windows 10 64 bit.

Looks like a simple fix to escape it - and probably the right brace too?

### hu.t
`>perl hu.t`
`1..21`
`Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.32), passed through in regex; marked by <-- HERE in m/window[.]dataSourceResults=({ <-- HERE .+})</script>/ at C:/Utility/Strawberry/perl/site/lib/Finance/Quote/HU.pm line 102.`
`ok 1`
`ok 2`
`ok 3`
`ok 4`
`ok 5`
`ok 6`
`ok 7`
`not ok 8`
`#   Failed test at hu.t line 53.`
`Use of uninitialized value within %quotes in numeric gt (>) at hu.t line 54.`
`not ok 9`
`#   Failed test at hu.t line 54.`
`Use of uninitialized value within %quotes in numeric gt (>) at hu.t line 55.`
`not ok 10`
`#   Failed test at hu.t line 55.`
`Use of uninitialized value in substr at hu.t line 57.`
`Argument "" isn't numeric in numeric eq (==) at hu.t line 57.`
`Use of uninitialized value in substr at hu.t line 57.`
`Argument "" isn't numeric in numeric eq (==) at hu.t line 57.`
`not ok 11`
`#   Failed test at hu.t line 57.`
`Use of uninitialized value in substr at hu.t line 59.`
`substr outside of string at hu.t line 59.`
`Use of uninitialized value in numeric eq (==) at hu.t line 59.`
`Use of uninitialized value in substr at hu.t line 59.`
`substr outside of string at hu.t line 59.`
`Use of uninitialized value in numeric eq (==) at hu.t line 59.`
`not ok 12`
`#   Failed test at hu.t line 59.`
`Use of uninitialized value within %quotes in string eq at hu.t line 60.`
`not ok 13`
`#   Failed test at hu.t line 60.`
`ok 14`
`ok 15`
`ok 16`
`ok 17`
`ok 18`
`ok 19`
`ok 20`
`ok 21`
`# Looks like you failed 6 tests of 21.`

### yahoojson.t
`>perl yahoojson.t`
`1..67`
`Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.32), passed through in regex; marked by <-- HERE in m/window[.]dataSourceResults=({ <-- HERE .+})</script>/ at C:/Utility/Strawberry/perl/site/lib/Finance/Quote/HU.pm line 102.`
`ok 1 - Data returned`
`ok 2 - Retrieved SUZLON.BO`
`ok 3 - Name is defined : SUZLON.BO (SUZLON ENERGY LTD.)`
`ok 4 - correctly retrieved through YahooJSON`
`ok 5 - fetch_method is yahoo_json`
`ok 6 - Last 5.57 > 0`
`ok 7 - Volume 6547145 > 0`
`ok 8 - Symbol type EQUITY`
`ok 9 - Bombay stocks have currency INR`
`ok 10 - Retrieved RECLTD.NS`
`ok 11 - Name is defined : RECLTD.NS (REC LTD)`
`ok 12 - correctly retrieved through YahooJSON`
`ok 13 - fetch_method is yahoo_json`
`ok 14 - Last 144.4 > 0`
`ok 15 - Volume 8731097 > 0`
`ok 16 - Symbol type EQUITY`
`ok 17 - Retrieved AMZN`
`ok 18 - Name is defined : AMZN (Amazon.com, Inc.)`
`ok 19 - correctly retrieved through YahooJSON`
`ok 20 - fetch_method is yahoo_json`
`ok 21 - Last 3000.46 > 0`
`ok 22 - Volume 5388551 > 0`
`ok 23 - Symbol type EQUITY`
`ok 24 - Retrieved SOLB.BR`
`ok 25 - Name is defined : SOLB.BR (SOLVAY)`
`ok 26 - correctly retrieved through YahooJSON`
`ok 27 - fetch_method is yahoo_json`
`ok 28 - Last 105.35 > 0`
`ok 29 - Volume 216909 > 0`
`ok 30 - Symbol type EQUITY`
`ok 31 - Retrieved ^DJI`
`ok 32 - Name is defined : ^DJI (Dow Jones Industrial Average)`
`ok 33 - correctly retrieved through YahooJSON`
`ok 34 - fetch_method is yahoo_json`
`ok 35 - Last 31496.3 > 0`
`ok 36 - Volume 505347596 > 0`
`ok 37 - Symbol type INDEX`
`ok 38 - Retrieved BEL20.BR`
`ok 39 - Name is defined : BEL20.BR (BEL 20)`
`ok 40 - correctly retrieved through YahooJSON`
`ok 41 - fetch_method is yahoo_json`
`ok 42 - Last 3498.04 > 0`
`ok 43 - Symbol type INDEX`
`ok 44 - Retrieved INGDIRECTFNE.BC`
`ok 45 - Name is defined : INGDIRECTFNE.BC (ING Direct FN Euro Stoxx 50 FI)`
`ok 46 - correctly retrieved through YahooJSON`
`ok 47 - fetch_method is yahoo_json`
`ok 48 - Last 12.05 > 0`
`ok 49 - Symbol type MUTUALFUND`
`ok 50 - Barcelona stocks have currency EUR`
`ok 51 - Retrieved AENA.MC`
`ok 52 - Name is defined : AENA.MC (AENA, S.M.E., S.A.)`
`ok 53 - correctly retrieved through YahooJSON`
`ok 54 - fetch_method is yahoo_json`
`ok 55 - Last 140.4 > 0`
`ok 56 - Volume 165402 > 0`
`ok 57 - Symbol type EQUITY`
`ok 58 - Madrid stocks have currency EUR`
`ok 59 - Retrieved CFR.JO`
`ok 60 - Name is defined : CFR.JO (Compagnie Fin Richemont)`
`ok 61 - correctly retrieved through YahooJSON`
`ok 62 - fetch_method is yahoo_json`
`ok 63 - Last 142.98 > 0`
`ok 64 - Volume 1425033 > 0`
`ok 65 - Symbol type EQUITY`
`ok 66 - Johannesburg stocks have currency ZAR`
`ok 67 - BOGUS failed`
``

**Comment by CleanShed** [comment]
Hi @vincentl , I will do a fix for this problem in HU.pm, and also clean up hu.t

**Comment by vincentl** [comment]
thanks.  just open a pull request when ready.

**Comment by vincentl** [comment]
I patched the regex.  @CleanShed - if you make more updates to HU.pm, please open a pull request.
