### ISSUE TITLE
Does FQ_LOAD_QUOTELET no longer support `-defaults`?

### ISSUE THREAD

**Issue by igoralmeida** [finance-quote/finance-quote#197]
Hi all,

I've been experimenting with gnucash quote sources and noticed that the documented behavior [here](https://github.com/finance-quote/finance-quote/blob/master/lib/Finance/Quote.pm#L1238) (i.e. `Note that the FQ_LOAD_QUOTELET environment variable must begin with '-defaults' if you wish the default modules to be loaded`) is not working.

Here's a simple test, basically the beginning of `gnc-fq-check`:
```
sh$ FQ_LOAD_QUOTELET=-defaults perl -w
require Finance::Quote;
Quote->import();
my $quoter = Finance::Quote->new();
```

Which gives me:
```
Can't locate Finance::Quote::-defaults in @INC (@INC contains:
/usr/lib/perl5/5.34/site_perl /usr/share/perl5/site_perl
/usr/lib/perl5/5.34/vendor_perl /usr/share/perl5/vendor_perl
/usr/lib/perl5/5.34/core_perl /usr/share/perl5/core_perl)
at /usr/share/perl5/core_perl/Module/Load.pm line 72.
```

I think it errors out because `-defaults` is only checked for in the arguments to `new`, not in `_load_modules` after honoring `FQ_LOAD_QUOTELET`: https://github.com/finance-quote/finance-quote/blob/master/lib/Finance/Quote.pm#L383-L399

Am I missing something?

Best regards

**Comment by bpschuck** [comment]
The `FQ_LOAD_QUOTELET` environment variable is normally not needed or used. It is set when the user wants to load a module that is not part of the F::Q package. An example of this would be `Sberbank` module ([Finance-Quote-Sberbank-0.04.readme](https://www.cpan.org/authors/id/K/KI/KILORK/Finance-Quote-Sberbank-0.04.readme)).
In addition you are setting the environment incorrectly. You would want to put quotes around the entire line after the `=` sign.
`FQ_LOAD_QUOTELET="-defaults <non default modulename>"`

**Comment by igoralmeida** [comment]
Thanks for the reply. I am aware of that and know how to populate an environment variable, and it is precisely because I am adding my own quote source that I need `FQ_LOAD_QUOTELET`. Once I point `PERL5LIB` to the correct place, my source does show up -- unless I use `-defaults`.

Did you confirm yourself that `FQ_LOAD_QUOTELET="-defaults YahooJSON" gnc-fq-check` works on your end?  Equivalently, if you don't have gnucash, my simple test above should just finish silently.
It does not work for me. Replace `-defaults` with something like `AEX` and you should see `("1.51" "aex" "dutch" "yahoo_json")`.

**Comment by igoralmeida** [comment]
I'd be happy to, once it's anywhere close to usable :)
Right now it is basically copy/paste from some old example I found elsewhere and it doesn't always work.

Thanks for the ack

**Comment by bpschuck** [comment]
It may be a few months before the next release, but add these 4 lines after line 393 in Quote.pm:

        if ($load_modules[0] eq '-defaults') {
          shift @load_modules;
          push(@load_modules, @MODULES);
        }
