### ISSUE TITLE
did not run 

### ISSUE THREAD

**Issue by kerwinxu** [finance-quote/finance-quote#204]
- Win 10 
- Gnucash 4.9+(2021-12-18)
- china
- Activeperl 

kerwin@KERWIN-PC D:\Program Files (x86)\gnucash\bin
$ perl gnc-fq-check
("1.49" "adig" "aex" "aiahk" "alphavantage" "amfiindia" "asegr" "asx" "aufunds" "australia" "bamosz" "bet" "bmonesbittburns" "bourso" "bse" "bsero" "canada" "canadamutual" "citywire" "cominvest" "cse" "deka" "dutch" "dwsfunds" "europe" "fetch_live_currencies" "fidelity" "fidelity_direct" "fidelityfixed" "financecanada" "finanzpartner" "finland" "fool" "france" "ftfunds" "ftportfolios" "ftportfolios_direct" "fundlibrary" "goldmoney" "greece" "hex" "hu" "hufund" "hungary" "hustock" "iexcloud" "indiamutual" "known_currencies" "lerevenu" "maninv" "morningstar" "morningstarau" "morningstarch" "morningstarjp" "mstaruk" "nasdaq" "nyse" "nz" "nzx" "platinum" "romania" "seb_funds" "sixfunds" "sixshares" "stockhousecanada_fund" "tdefunds" "tdwaterhouse" "tiaacref" "tnetuk" "troweprice" "troweprice_direct" "trustnet" "tsp" "tsx" "uk_unit_trusts" "ukfunds" "unionfunds" "usa" "usfedbonds" "vanguard" "vwd" "yahoo_json" "yahoo_yql" "za" "za_unittrusts")

I start the program of guncash , but it did not run ( check Finance::Quote )

my gmake is mingw32-make.exe of msys2 , I didn't use perl in msys because the installation was not successful .

**Comment by bpschuck** [comment]
What did not run? GnuCash? The output of `gnc-fq-check` indicates that the Finance::Quote module is installed and working. You can also check fetching a quote with `gnc-fq-dump yahoo_json ibm`. This appears to be an issue with GnuCash recognizing that F::Q is installed. I suggest you contact the gnucash-user email list. Another reason that users have had issues is that multiple versions or distributions of Perl are installed (On Windows having Active State and Strawberry Perl for example).

**Comment by bpschuck** [comment]
Also note, GnuCash should run whether or not Finance::Quote is installed.
Ensure that the gnc-fq-xxxx tools are in your `%PATH%`.

**Comment by bpschuck** [comment]
Issue will be closed with no action 03/19/2022.

**Comment by kerwinxu** [comment]
> 

$ perl gnc-fq-dump yahoo_json ibm
Finance::Quote fields Gnucash uses:
    symbol: ibm                  <=== required
      date: ** missing **        <=== recommended
  currency: ** missing **        <=== required
      last: **missing**          <=\
       nav: **missing**          <=== one of these
     price: **missing**          <=/
  timezone:                      <=== optional

** This stock quote cannot be used by GnuCash!

kerwin@KERWIN-PC D:\Program Files (x86)\gnucash\bin
$ where perl
C:\Users\kerwin\AppData\Local\activestate\cache\bin\perl.bat
D:\msys64\mingw64\bin\perl.exe
D:\msys64\usr\bin\perl.exe


"dit not run" means  Lost response ， it always " check Finance::Quote " .

**Comment by bpschuck** [comment]
With at least 2 different paths with a `perl.exe`, your issue is likely a problem with there being multiple library paths (@INC in Perl). If you recently installed F::Q, release 1.51 should be the reported version, not 1.49. It was released about a year ago.

**Comment by kerwinxu** [comment]
> With at least 2 different paths with a `perl.exe`, your issue is likely a problem with there being multiple library paths (`@INC` in Perl). If you recently installed F::Q, release 1.51 should be the reported version, not 1.49. It was released about a year ago.

Thank you for you reply ， about 1.49 , because my perl is activeperl , I install F::Q through  "state install Finance::Quote " , my system is win10 , "cpan  Finance::Quote" is not ok  whether it's activeperl or perl of msys .

This problem is most likely gnucash's problem , there is not such problem in my ubuntu (virtualbox) . i already send email to gnucash-user

**Comment by bpschuck** [comment]
BTW - Recommended Perl for Windows for GnuCash >2.5 is Strawberry Perl. See [Online Quotes - Perl on Windows](https://wiki.gnucash.org/wiki/Online_Quotes#Installing_Perl_on_Windows).

**Comment by bpschuck** [comment]
Issue is user environment/configuration and not Finance::Quote. Closing issue.
