### ISSUE TITLE
Import Stock or Fund Transactions

### ISSUE THREAD

**Issue by LadyPebbles** [finance-quote/finance-quote#225]
To whom it may concern:

I've tried importing transactions containing Price information for stocks; all I get are very wrong shares, price, debit, and credit information. Github won't attach the jpg file I made of a screenshot so I will try to describe what is happening. 

The transaction is to record realized capital gains that have been reinvested. No money has changed hands. Instead, the number of shares is increased. All the text and date fields import correctly.

1. The imported price is the only imported number appropriately placed in the correct column: the debit column of the stock split i.e. the first line of the splits.
2. The calculated number of shares is correct but it is placed incorrectly; in the credit column on the next split line of the income account for realized gains.
3. The imported price is not placed in the price column. Instead, "1" is placed there and the number of shares on that line is the same as the imported deposit. 
4. The automatic balancer forces me to enter another stock split (a third split line) on which it places the credit amount equal to the deposit amount. This credit should be on the previous line where the number of shares was erroneously posted. 

I've read through all the help files I can find and have come to the conclusion that the import of stock data is a work in progress for you. I completely understand if this is true. If so, please point me to more concise instructions that can help me find out if I'm importing data correctly. Thank you.

**Comment by bpschuck** [comment]
@LadyPebbles - Finance::Quote is the mechanism used to fetch current security and currency pricing from various sources available on the internet. 

Importing data from csv, xml, or other files is **not** a function of F::Q. I suggest you reach out to the gnucash-user@gnucash.org email list.

Thank you.

**Comment by LadyPebbles** [comment]
Dear @bpschuck ,

Thank you for your quick reply. I've already imported all the historical price data for my securities. My original post is for importing the historical general journal transactions that record realized capital gains, dividends, and recurring purchases. I'm sorry for the confusion and I have updated my original post for clarity.

**Comment by bpschuck** [comment]
Still,importing is a function of GnuCash itself (I'm assuming you are importing data into GnuCash) and *NOT* Finance::Quote.

The GnuCash documentation in importing transactions is at https://www.gnucash.org/docs/v4/C/gnucash-help/trans-import.html.

Once again, please reach out to the community on the gnucash-user@gnucash.org email list. The are usually extremely helpful.

Thank you.
