### ISSUE TITLE
AlphaVantage.co function CURRENCY_EXCHANGE_RATE no longer accepts free API keys.

### ISSUE THREAD

**Issue by JDLH** [finance-quote/finance-quote#229]
I use Finance::Quote via GnuCash. Sometime after 1. August 2022, foreign exchange lookups started failing. 

It appears that Finance::Quote uses the CURRENCY_EXCHANGE_RATE function of the AlphaVantage API. Source: [lib/Finance/Quote/CurrencyRates/AlphaVantage.pm#L56](https://github.com/finance-quote/finance-quote/blob/0cfaced5ca98e7cd01ede237a73d3a70f40e2403/lib/Finance/Quote/CurrencyRates/AlphaVantage.pm#L56). 

Looking at the AlphaVantage API documentation, I see that the [CURRENCY_EXCHANGE_RATE function](https://www.alphavantage.co/documentation/#currency-exchange) is (now) marked "Premium", but the [FX_DAILY function](https://www.alphavantage.co/documentation/#fx-daily) is not.

I just tried using both endpoints, using my free API key. I got an error message for CURRENCY_EXCHANGE_RATE, but I got a response for FX_DAILY. See below.

Now while CURRENCY_EXCHANGE_RATE returns near-real-time data, FX_DAILY returns the most recent 100 days at minimum, and can return more.  That works fine for me as a GnuCash user. Could Finance::Quote and GnuCash switch to using FX_DAILY? I would be delighted if one call to Get Quotes in GnuCash gave me 100 days of exchange rate history!

This issue is the subject of [GnuCash bug 798599](https://bugs.gnucash.org/show_bug.cgi?id=798599). There is discussion of this issue on the [GnuCash-user email list, in thread "Online Currency Exchange Rates"](https://lists.gnucash.org/pipermail/gnucash-user/2022-August/102424.html).

Example of exercising the AlphaVantage API functions with a free API key (elided here):
```
% curl "https://www.alphavantage.co/query?function=CURRENCY_EXCHANGE_RATE&from_symbol=EUR&to_symbol=USD&apikey=elided"
{
    "Information": "Thank you for using Alpha Vantage! This is a premium endpoint. You may subscribe to any of the premium 
    plans at https://www.alphavantage.co/premium/ to instantly unlock all premium endpoints"
}
% curl "https://www.alphavantage.co/query?function=FX_DAILY&from_symbol=EUR&to_symbol=USD&apikey=elided"
{
    "Meta Data": {
        "1. Information": "Forex Daily Prices (open, high, low, close)",
        "2. From Symbol": "EUR",
        "3. To Symbol": "USD",
        "4. Output Size": "Compact",
        "5. Last Refreshed": "2022-08-15 03:00:00",
        "6. Time Zone": "UTC"
    },
    "Time Series FX (Daily)": {
        "2022-08-15": {
            "1. open": "1.02570",
            "2. high": "1.02683",
            "3. low": "1.02380",
            "4. close": "1.02470"
        },
        "2022-08-14": {

…[elided]…

        },
        "2022-03-28": {
            "1. open": "1.09938",
            "2. high": "1.11363",
            "3. low": "1.09705",
            "4. close": "1.09938"
        }
    }
}
```

**Comment by bpschuck** [comment]
Thank you for the heads up.
Personally I am not going to be able to look at this anytime soon due to a family matter (I'll have spotty free time for about the next 2 or 3 weeks).
Hopefully someone else may be able to make the appropriate changes so myself or another team member can merge any pull request.
Thank you.

**Comment by shirayu** [comment]
Actually, I just started the fix a few hours ago.
I think this pull request will fix it.

**Comment by JDLH** [comment]
I have checked PR #230 from within macOS and within GnuCash 4.10, and it seems to work correctly.  Thank you!
