### ISSUE TITLE
Cannot import from AEX to Gnucash

### ISSUE THREAD

**Issue by albedorsch** [finance-quote/finance-quote#235]
I can quote from aex via gnc-fq-dump, but I can't import these values into Gnucash.
On IRC #gnucash I was told that "AEX must have changed their webpage and broken the scraper in AEX" and that I should file a bug here.
Voilà. Your help is appreciated! 

[alex@x270 ~]$ gnc-fq-dump -v aex exs1
Use of uninitialized value $info{"exs1\34volume"} in substitution (s///) at /usr/share/perl5/site_perl/Finance/Quote/AEX.pm line 139.
Finance::Quote fields Gnucash uses:
    symbol: exs1 (deduced)       <=== required
      date: 09/30/2022           <=== recommended
  currency: ** missing **        <=== required
      last: 102.168              <=\
       nav:                      <=== one of these
     price:                      <=/
  timezone:                      <=== optional

** This stock quote cannot be used by GnuCash!

All fields returned by Finance::Quote for stock exs1

stock           field  value
-----           -----  -----
Use of uninitialized value in printf at /usr/bin/gnc-fq-dump line 138.
exs1         currency: 
exs1             date: 09/30/2022
exs1             high: 102.361
exs1             isin: NSCFR0IEXS10
exs1          isodate: 2022-09-30
exs1             last: 102.168
exs1              low: 101.001
exs1             name: ISHARES EXS1 INAV
exs1             open: 101.001
exs1          success: 1
Use of uninitialized value in printf at /usr/bin/gnc-fq-dump line 138.
exs1           volume: 

[alex@x270 ~]$ gnc-fq-dump -v aex cv9
Use of uninitialized value $info{"cv9\34volume"} in substitution (s///) at /usr/share/perl5/site_perl/Finance/Quote/AEX.pm line 139.
Finance::Quote fields Gnucash uses:
    symbol: cv9 (deduced)        <=== required
      date: 09/30/2022           <=== recommended
  currency: ** missing **        <=== required
      last: 217.241              <=\
       nav:                      <=== one of these
     price:                      <=/
  timezone:                      <=== optional

** This stock quote cannot be used by GnuCash!

All fields returned by Finance::Quote for stock cv9

stock           field  value
-----           -----  -----
Use of uninitialized value in printf at /usr/bin/gnc-fq-dump line 138.
cv9          currency: 
cv9              date: 09/30/2022
cv9              high: 218.674
cv9              isin: NSCFR0INCV92
cv9           isodate: 2022-09-30
cv9              last: 217.241
cv9               low: 215.008
cv9              name: AMUNDI CV9 INAV
cv9              open: 215.008
cv9           success: 1
Use of uninitialized value in printf at /usr/bin/gnc-fq-dump line 138.
cv9            volume: 

[alex@x270 ~]$ gnucash-cli --quotes get /home/alex/Documents/finance/gnucash/budget.gnucash
Found Finance::Quote version 1.52.
* 11:23:01  WARN <gnc.scm> Unable to retrieve quotes for these items:
XETRA:EXS1
  EURONEXT:CV9
  CURRENCY:BRL
  CURRENCY:USD
  CURRENCY:EUR
  CURRENCY:GBP
  CURRENCY:ARS
  CURRENCY:CNY
  CURRENCY:PEN
  CURRENCY:SEK
  CURRENCY:NOK
  CURRENCY:DKK
Continuing with good quotes.

**Comment by bpschuck** [comment]
Thank you. May not be addressed until v1.54.

**Comment by bpschuck** [comment]
A user figuring out which symbol or ISIN to use at this point is a red herring. But even a fund needs to know what currency the value represents. It may be a while before I can get to this. Of course it's appreciated if anyone reworks the module and creates a pull request.

**Comment by Andre-J** [comment]
I get the ISIN when I buy a fund or share via my bank, at least in Europe. Finding out the symbols is much more embarrasing for me, as they change from source to source, and sometimes (eg Yahoo) even between the same share at different exchanges.
The IEXS1 is an Index, not a fund. It seems the Euronext has added some index values to their database, making the symbol EXS1 unusuable for our purpose.
The AEX.pm fails here because the values for Currency and Volume are not set for IEXS1 (but are for correct funds and shares like EXS1). The error message about the substitution is with the Volume value, but that is not used by GnuCash.

**Comment by bpschuck** [comment]
@Andre-J,
Thank you for the analysis. I'm thinking that while the module could be enhanced to do a better job of parsing the responses returned, the issue reported is more of a user problem where using the ISIN (DE0005933931) instead of the symbol (EXS1) would return data that GnuCash can utilize. Do you agree @albedorsch?

**Comment by bpschuck** [comment]
That said, I have done some rewriting of the logic to skip indices. I've also started to remove calls to die and instead set hash values for success and errormsg (errormsg may be used in future releases of GnuCash for better handling of bad results being returned). Using this logic I can also remove the `eval` blocks.
Not sure if these changes will be officially released in v1.54 or perhaps a v1.5302 bug fix release.

**Comment by rsbrux** [comment]
At first I too was put off by the suffixes Yahoo uses to distinguish between quotes from different exchanges, but I now consider it advantageous, as I am generally interested in the quotes from my home market or those used by my brokers.

**Comment by Andre-J** [comment]
> At first I too was put off by the suffixes Yahoo uses to distinguish between quotes from different exchanges, but I now consider it advantageous, as I am generally interested in the quotes from my home market or those used by my brokers.

You may be correct, but this example made me turn away from Yahoo:

ABN AMRO Bank shares have the Yahoo symbol ABN.AS for the Amsterdam exchange, but for the Frankfurt exchange, it is either AB2.F or AB2A.F, with different prices. Not sure what the sense behind that is.

**Comment by bpschuck** [comment]
@albedorsch,
If you are comfortable with installing F::Q directly from GitHub, give the current repo a try.
