### ISSUE TITLE
Unable to install Version 1.53 Release Candidate 1

### ISSUE THREAD

**Issue by yugui** [finance-quote/finance-quote#236]
The release candidate requires LWP::Protocol::https 6.48. However, cpan and cpanm cannot find the version of the library.
They could find just 6.10 https://metacpan.org/pod/LWP::Protocol::https.

**Comment by bpschuck** [comment]
The error while building can be ignored. CPAN usually skips it and moves on. At least that has been my experience.
Made a mistake while fixing the requirements.
