### ISSUE TITLE
The tdwaterhouse and tdefunds sources are broken

### ISSUE THREAD

**Issue by rdegraaf** [finance-quote/finance-quote#24]
The tdwaterhouse and tdefunds quote sources have been broken for some months, presumably because TD changed how their web site works.  

So I wrote a new source for TD that works with their current site, and wrote another source to use the deprecated but still available Google Finance API while I was at it.  Feel free to merge them in from https://github.com/rdegraaf/Finance-Quote-addons.

**Comment by vincentl** [comment]
Neither of the modules in https://github.com/rdegraaf/Finance-Quote-addons appear to work any longer.  Closing this issue.

If either module can be updated to work, please consider forking https://github.com/finance-quote/finance-quote, adding the new modules, and then opening a pull request.
