### ISSUE TITLE
New Module request - custom/localhost

### ISSUE THREAD

**Issue by Kaligula0** [finance-quote/finance-quote#242]
I have a few securities, which I periodically check the price of, but they don't have any public API or it's hard to reach or is subject to change or it would need webscraping or even PDF-scraping. I'd like to automate this, hence my request.

Do you consider / is it possible to add a custom-module that requests localhost? localhost, local file or whatever (maybe someone has a better idea). That anyone could get prices the way he wants (webscraping, downloading as database, export calculations from Excel or whatever) and present it to this module in a specific standard (JSON?) response.

**Comment by bpschuck** [comment]
GnuCash already has the capability to import stock prices from CSV without using F::Q.

**Comment by Kaligula0** [comment]
Oh, you're right. Thanks!
So, if you're not interested in implementing this into F::Q then you can close it :)
