### ISSUE TITLE
Finance::Quote currency lookup for XAU/XAG failing

### ISSUE THREAD

**Issue by zinglo** [finance-quote/finance-quote#246]
I just updated to 1.5301 via CPAN (previously on 1.47).

Previously I could get gold/silver prices with:
foreach my $sym (qw(XAU XAG)) {
   my $rate = $q->currency($sym, "USD");
   print "$sym: $rate\n";
}

Now I get nothing.
Queries to alphavantage still seem to work with:
https://www.alphavantage.co/query?function=CURRENCY_EXCHANGE_RATE&from_currency=XAU&to_currency=USD&apikey=XXX

**Comment by bpschuck** [comment]
A few months ago, AlphaVantage changed the `CURRENCY_EXCHANGE_RATE` API to require a Premium API Key. The module was changed to utilize the `FX_DAILY` API (see Issue #229 and Pull Request #230) which does not include Crypto and Precious Metals. Annoying, it seems that AlphaVantage has recently reversed that requirement.
In the meantime, try downgrading to v1.52 (check the `Changes` file for v1.53 features which may affect you).
Thanks for heads up.
