### ISSUE TITLE
Some currency pairs are not available directly but could be obtained via a detour.

### ISSUE THREAD

**Issue by zommuter** [finance-quote/finance-quote#258]
Trying to get XAU-CHF (via gnucash using alphavantage) I noticed that pair does not exist, so I submitted https://github.com/Gnucash/gnucash/pull/1487 to add an indirect XAU-EUR / CHF-EUR lookup. However I was told this logic should be here, hence this issue - sorry, I'm not too deep in the source so I probably won't be able to PR this myself anytime soon.

**Comment by Kaligula0** [comment]
GnuCash can deal with all budget calculations if you get just XAU-USD and USD-CHF (I do so) or XAU-EUR and CHF-EUR (like you wrote).

**Comment by zommuter** [comment]
@Kaligula0 True, but if you use the online quotes feature it uses your locale, in my case CHF, so instead of said detour I previously only got a meaningless "Unable to retrieve quotes". Of course an alternative to my suggestion would be a possibility to set up gnucash to use a different base currency without changing the locale...

**Comment by bpschuck** [comment]
F::Q and its various modules can only fetch data available from the various sources. Adding an indirect lookup would be the function of the program/script calling F::Q.

**Comment by zommuter** [comment]
@bpschuck Thanks, makes more sense to me as well 👍

**Comment by bpschuck** [comment]
The correct solution would be to find a Swiss based source for precious metal quotes and create a new module specifically for that source. The create an indirect calculation for every conceivable currency pair not readily available from AlphaVantage or Yahoo would be trip down the old rabbit hole.

**Comment by zommuter** [comment]
No worries, I automated that detour from `currency($to, $from)` to `currency($to, "EUR") / currency($from, "EUR")`, but still agree, too many possibilities... Unfortunately I haven't figured out how to let gnucash use a different source for "currencies" (as which it considers gold in a hardcoded way it seems), so the other workaround would be changing my default currency there.
