### ISSUE TITLE
cannot get quotes in gnucash

### ISSUE THREAD

**Issue by tijo82** [finance-quote/finance-quote#259]
I can't get any quotes in gnucash anymore using alphavantage.

A manual call using my API key and the symbol works just fine, e.g: 
https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=AEEM.PA&apikey=<key>

I did not change any of my configuration ... will I have to?

Thanks
Tim

**Comment by bpschuck** [comment]
Happy New Year!

Sorry for your issues, but not getting the quotes in GnuCash is _not_ a F::Q problem. 

Two possible causes are a configuration issue in GnuCash, or something related to your Perl installation(s) and the search path where Perl looks for modules.

It's also appreciated by any bug reporting tool that the description of the issue includes OS and software versions.

While I may be able to provide pointers and suggestions, this issue will be closed.

Thank you.
