### ISSUE TITLE
Finance::Quote::FTfunds not finding some quotes

### ISSUE THREAD

**Issue by jrjove** [finance-quote/finance-quote#266]
Since beginning of april, finance quote fails to retrieve some fund prices such as:

ES0165237019
ES0115086029
BE6246061376
whith he error code: Error - failed to retrieve fund data

Kind regards

**Comment by bpschuck** [comment]
Need more information. What OS, what version of F::Q, how are you attempting to fetch quotes (standalone perl program, from within GnuCash or another finance application)?

Likely a Perl library configuration issue. 

```
./stockdump.pl ftfunds BE6246061376 
$VAR1 = {
          'BE6246061376net' => '-0.00',
          'BE6246061376price' => '244.50',
          'BE6246061376name' => 'DPAM B - Equities NewGems Sustainable W Cap, BE6246061376:EUR',
          'BE6246061376errormsg' => 'Warning - failed to find a time',
          'BE6246061376symbol' => 'BE6246061376',
          'BE6246061376method' => 'ftfunds',
          'BE6246061376nav' => '244.50',
          'BE6246061376time' => '17:00',
          'BE6246061376last' => '244.50',
          'BE6246061376p_change' => '-0.00',
          'BE6246061376success' => 1,
          'BE6246061376isodate' => '2023-04-28',
          'BE6246061376date' => '04/28/2023',
          'BE6246061376source' => 'https://markets.ft.com/data/funds/tearsheet/summary?s=BE6246061376',
          'BE6246061376currency' => 'EUR'
        };
```

**Comment by bpschuck** [comment]
Sorry, there was a minor fix required that will be in the next release. In FTfunds.pm the line

`m[<span class="mod-ui-data-list__label">Price [(]([A-Z]{3})[)]</span><span class="mod-ui-data-list__value">([\.\,0-9]*)</span>]  )`

has been changed to

`m[<span class="mod-ui-data-list__label"[^>]*>Price [(]([A-Z]{3})[)]</span><span class="mod-ui-data-list__value">([\.\,0-9]*)</span>]  )`

**Comment by bpschuck** [comment]
This is fixed in https://github.com/finance-quote/finance-quote/pull/262. Closing issue.
