### ISSUE TITLE
Finance::Quote fails to retrieve quotes with tradeville method

### ISSUE THREAD

**Issue by besteru** [finance-quote/finance-quote#269]
seems that the tradevile.ro page no longer returns a static HTML that can be parsed.
It now returns a page that refers to a big separate .js file that looks that is doing all rendering.

In order for tradeville method to work, the .js should be executed.

as an alternative to retrieve quotes for BVB, the main BVB site return a static page with all the quote data (but in different places/different tags:
https://bvb.ro/FinancialInstruments/Details/FinancialInstrumentsDetails.aspx?s=BRD

**Comment by bpschuck** [comment]
Thank you for the notification. It may be some time before one of the F::Q team members can address this. However, anyone else is free to tackle the issue or create a BVB.pm module and submit a pull request.
It's also helpful to include example symbols for querying data. While the test files (in this case tradeville.t) will have symbols, sometimes they symbols that at outdated and no longer in use.
Thank you.

**Comment by bpschuck** [comment]
@besteru, I'm looking at the bvb.ro source noted. What I don't see is a currency specifically returned in the HTML. But, looking at the a few non-Romanian securities like [ADS](https://bvb.ro/FinancialInstruments/Details/FinancialInstrumentsDetails.aspx?s=ADS), it seems that all prices are returned in RON. Is that a safe assumption if a BVB.pm was created to replace Tradeville.pm?

**Comment by besteru** [comment]
BVB is the main site of the Bucharest Stock Exchange (Bursa de Valori Bucuresti). So all prices are in RON. 
Tradeville.pm had the alias as "romania" so its main purpose was to return the Romanian stocks. It does not make much sense to retrieve NYSE stocks in RON... But we need a way to retrieve BVB stocks. And currencies can be converted.

**Comment by bpschuck** [comment]
@besteru If you are comfortable with manipulating files in your Perl library trees, I believe I have a BVB.pm module just about ready. You may need to edit your Quote.pm module depending on what your current F::Q version is. There are a few other changes coming in v1.56 that are already represented in my branch at https://github.com/bpschuck/finance-quote/tree/bvb. I _may_ push a 1.55_02 to CPAN later this weekend, but it could be a few days instead. I still need to remove Tradeville.pm and references to it and some other cleanup (sometimes the housekeeping in preparing for an official release is more burdensome than the coding work itself).
