### ISSUE TITLE
Failed to install via perl

### ISSUE THREAD

**Issue by lodenrogue** [finance-quote/finance-quote#275]
Tried installing Finance::Quote on a new M2 Macbook Air.

Ran the following command:

```
perl -MCPAN -e shell
cpan[1]> install Finance::Quote
```

It went through the build cycle and in the end the tests failed:

```
Test Summary Report
-------------------
t/nzx.t                  (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
Files=62, Tests=82,  4 wallclock secs ( 0.05 usr  0.05 sys +  3.18 cusr  0.66 csys =  3.94 CPU)
Result: FAIL
Failed 1/62 test programs. 0/82 subtests failed.
make: *** [test_dynamic] Error 255
  BPSCHUCK/Finance-Quote-1.55.tar.gz
2 dependencies missing (DateTime::Format::ISO8601,DateTime::Format::Strptime); additionally test harness failed
  /usr/bin/make test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports BPSCHUCK/Finance-Quote-1.55.tar.gz
Failed during this command:
 DROLSKY/DateTime-Locale-1.38.tar.gz          : make_test NO
 DROLSKY/DateTime-Format-Strptime-1.79.tar.gz : make_test NO
 DROLSKY/DateTime-Format-Builder-0.83.tar.gz  : make_test NO one dependency not OK (DateTime::Format::Strptime); additionally test harness failed
 DROLSKY/DateTime-Format-ISO8601-0.16.tar.gz  : make_test NO one dependency not OK (DateTime::Format::Builder); additionally test harness failed
 BPSCHUCK/Finance-Quote-1.55.tar.gz           : make_test NO 2 dependencies missing (DateTime::Format::ISO8601,DateTime::Format::Strptime); additionally test harness failed
 ```
 
 Please let me know if you need any more info

**Comment by crowedavid** [comment]
This happened to me on Apple Silicon Macs due to arch (x86_64 vs arm64) differences. Assuming you are running this for GnuCash, if you run "gnc-fq-update" (usually in /Applications/Gnucash.app/Contents/Resources/bin/) it updated correctly for me.

**Comment by lodenrogue** [comment]
I'm using this for GnuCash and I tried this suggestion both with sudo and without but GnuCash still says "Warning: Finance::Quote not installed properly".

**Comment by lodenrogue** [comment]
The suggestion does seem to fix the perl install though. Output is now:

```
cpan[1]> install Finance::Quote
Reading '/Users/juno/.cpan/Metadata'
  Database was generated on Mon, 15 May 2023 20:54:04 GMT
Finance::Quote is up to date (1.55).
```

But no luck getting GnuCash to recognize it. I'll keep trying some other things. We can close this issue if you want.

**Comment by crowedavid** [comment]
GnuCash runs under Rosetta 2 on Apple Silicon Macs while the native perl runs native so you may be in a situation where part of Finance::Quote was compiled with arm64 and GnuCash won't be able to run it. You might need a clean slate and restart CPAN install using gnc-fq-update for the whole thing.

This is getting more into macOS/GnuCash support than strictly for Finance::Quote so it might be best to move to the gnucash-users mailing list.

**Comment by bpschuck** [comment]
Yes, OSX can be problematic where Perl is concerned. For those that may do Perl development, sometimes playing with installing modules down different paths can make a mess. 
I found that on my work M1 Macbook Pro that updating the `Test2` module before installing `Finance::Quote` did the trick.

If you have never run CPAN before, it may help to start it and let it build the config file and add environment variables to your `.zshrc` (or `.bashrc`) file for you. Then log out and log back in (or source your newly modified `.zshrc` or `.bashrc` file before attempting to install `Finance::Quote`.

Unfortunately my MacBook used for testing is an older model running Catalina. Work frowns using their equipment for personal projects. As of yet, no one has donated a new M1 or M2 Macbook to the Finance::Quote team... <snicker>

Thanks to everyone who suggested workarounds.

**Comment by lodenrogue** [comment]
Not very familiar with perl. How do I uninstall F::Q and start fresh?

**Comment by marc-medley** [comment]
@lodenrogue @crowedavid @bpschuck Some notes regarding macOS Perl (x86_64 vs arm64) installations and GnuCash are here:

- [Install & update a Perl module as "universal" (x86_64, arm64)?](https://stackoverflow.com/questions/75983186/install-update-a-perl-module-as-universal-x86-64-arm64/76094938#76094938)

**Comment by crowedavid** [comment]
this is more of a CPAN (perl module archive and installer) issue.  perl (and by extension CPAN) on macOS is a bit of a bugger in general so we're delving into a possible muddle if you aren't familiar with them.

one option is to force an install:

cpan -f -i Finance::Quote

unfortunately, CPAN doesn't have an uninstall option.

**Comment by marc-medley** [comment]
@crowedavid @lodenrogue  A `-f` force install with universal binary can avoid future native arm64 vs rosetta x86_64 issues.  Also GnuCash use of F::Q would need Test2, Finance::Quote and JSON::Parse.

``` sh
(sudo) env ARCHFLAGS='-arch arm64 -arch arm64e -arch x86_64' cpan -f -i Test2
(sudo) env ARCHFLAGS='-arch arm64 -arch arm64e -arch x86_64' cpan -f -i Finance::Quote
(sudo) env ARCHFLAGS='-arch arm64 -arch arm64e -arch x86_64' cpan -f -i JSON::Parse
```

**Comment by bpschuck** [comment]
And it's not F::Q that needs the `Test2` module. It's one of it's dependencies that requires it, and probably just to run its tests.

@lodenrogue - As David said, CPAN does not have an uninstall or remove. When CPAN asked how you want to install "sudo, local::lib, or manual", how did you answer?

**Comment by crowedavid** [comment]
> @crowedavid @lodenrogue A `-f` force install with universal binary can avoid future native arm64 vs rosetta x86_64 issues. Also GnuCash use of F::Q would need Test2, Finance::Quote and JSON::Parse.

thanks for the universal binary pointer - wish i'd known about that awhile ago. :-)

**Comment by bpschuck** [comment]
Closing issue per user comment.

> The suggestion does seem to fix the perl install though. Output is now:
> 
> ```
> cpan[1]> install Finance::Quote
> Reading '/Users/juno/.cpan/Metadata'
>   Database was generated on Mon, 15 May 2023 20:54:04 GMT
> Finance::Quote is up to date (1.55).
> ```
> 
> But no luck getting GnuCash to recognize it. I'll keep trying some other things. We can close this issue if you want.
