### ISSUE TITLE
Request: Document for the user the incidental installation dependency of Test2

### ISSUE THREAD

**Issue by marc-medley** [finance-quote/finance-quote#276]
**Request:** Document the _incidental installation dependency_ of `Test2` in the [README.md](https://github.com/finance-quote/finance-quote/blob/master/README.md) for the benefit of the end user.

**Related:** ["And it's not F::Q that needs the Test2 module."](https://github.com/finance-quote/finance-quote/issues/275#issuecomment-1548810894)

**Discussion:**

`Test2` may not be required as a code depency to "run" F::Q; however, `Test2` is currently required for a successful F::Q "install" … at least on macOS 13.

From a user viewpoint, `Test2` is "required" because if `Finance::Quote` is not _successfully installed_, then `Finance::Quote` never _runs_.

Thus, the "developer" and "user" views can differ, yet both are technically correct in their respective frame of reference.

The README could clarify both dependency contexts with some language such as:

``` sh
cpanm Test1  # Incidental use during install. Not a F::Q code dependency.
cpanm Finance::Quote
```

**Test Procedure:**

- Create a macOS 13.3.1 clean installation on a machine/drive dedicated to Perl install test purposes
- Install Xcode and Xcode Command Line Tools

_Test install without Test2_

- Install `App::cpanminus`
- Install `Finance::Quote`

``` sh
sudo cpan App::cpanminus

sudo cpanm Finance::Quote
# …
# ! Installing the dependencies failed: 
#    Module 'DateTime::Format::ISO8601' is not installed, 
#    Module 'DateTime::Format::Strptime' is not installed
# ! Bailing out the installation for Finance-Quote-1.55.
```

:RESULT:FAIL: Installation does not complete. _Apparently `DateTime` needed `Test2` for some reason._

- [fq-20-terminal.txt](https://github.com/finance-quote/finance-quote/files/11483531/fq-20-terminal.txt) full terminal console output
- [fq-21-build.log.txt](https://github.com/finance-quote/finance-quote/files/11483535/fq-21-build.log.txt) full build.log file

_Test install with Test2_

- Remove `$HOME/.cpan` and `$HOME/.cpanm`
- Restore /Library/Perl to original state

![Library~Perl](https://github.com/finance-quote/finance-quote/assets/15098151/be2ae1f3-ba5f-4865-adbc-1b7a81106b11)

- Install `App::cpanminus`
- Install `Test2`
- Install `Finance::Quote`

``` sh
sudo cpan App::cpanminus
sudo cpanm Test2

sudo cpanm Finance::Quote
# Building and testing Finance-Quote-1.55 ... OK
# Successfully installed Finance-Quote-1.55
# 68 distributions installed
```

:RESULT:PASS: Installation fully completed.

- [fq-30-terminal.txt](https://github.com/finance-quote/finance-quote/files/11483344/fq-30-terminal.txt) full terminal console output

_Run Simple Example_

- Create simple test example

``` perl
### File: fq-test-01.pl
use Finance::Quote;
use Data::Dumper; # only for array printing.

@stocks = ("NVDA");
$q = Finance::Quote->new;
%quotes = $q->fetch("yahoo_json", @stocks);

print Dumper(\%quotes);
```

- Run simple test example

``` sh
perl fq-test-01.pl 
# $VAR1 = {
#     'NVDAcurrency' => 'USD',
#     'NVDAdiv_yield' => '0.056457304',
#     'NVDAdate' => '05/15/2023',
# ...
```

:RESULT:PASS: Successfully installed Finance::Quote did successfully run & fetch a quote. Q.E.D.

**Comment by bpschuck** [comment]
Unfortunately it was Datetime::Locale that failed to install because of there being an insufficient version of Test2. Then F::Q could not install since Datetime::Locale would not install. To document missing dependencies cause other dependencies is beyond the scope of the F::Q Readme. I've seen this happen with many other modules over the years I've used Perl. And what happens if a new version of Test2 doesn't correctly identify a dependency? Document in F::Q that one needs to install/update Foo::Bar before updating/installing Test2 before installing F::Q?

**Comment by bpschuck** [comment]
Opened an issue with [DateTime::Locale](https://github.com/houseabsolute/DateTime-Locale/issues/36).

**Comment by bpschuck** [comment]
Seems it is an OSX issue with the pre-installed Perl.
See https://github.com/houseabsolute/DateTime-Locale/issues/36.
