### ISSUE TITLE
yahoo_json issue resurfaced 

### ISSUE THREAD

**Issue by avlsi** [finance-quote/finance-quote#282]
perl gnc-fq-dump -v yahoo_json AAPL
Finance::Quote fields Gnucash uses:
    symbol: AAPL                 <=== required
      date: ** missing **        <=== recommended
  currency: ** missing **        <=== required
      last: **missing**          <=\
       nav: **missing**          <=== one of these
     price: **missing**          <=/
  timezone:                      <=== optional

** This stock quote cannot be used by GnuCash!

All fields returned by Finance::Quote for stock AAPL

stock           field  value
-----           -----  -----
AAPL         errormsg: Error retrieving quote for AAPL. Attempt to fetch the URL https://query1.finance.yahoo.com/v6/finance/quote?symbols=AAPL resulted in HTTP response 404 (Not Found)
AAPL             last: **missing**
AAPL              nav: **missing**
AAPL            price: **missing**
AAPL          success: 0
AAPL           symbol: AAPL

**Comment by bpschuck** [comment]
For me it's still working (I still use a 4.x version of GnuCash). I executed this commands at 08:55AM PDT.

```
bruce.schuck@Bruces-MBP-2 ~ % gnc-fq-dump yahoo_json AAPL
Finance::Quote fields Gnucash uses:
    symbol: AAPL                 <=== required
      date: 05/24/2023           <=== recommended
  currency: USD                  <=== required
      last: 170.94               <=\
       nav:                      <=== one of these
     price:                      <=/
  timezone:                      <=== optional
  ```
  
  And the curl command:
  
  ```
 bruce.schuck@Bruces-MBP-2 ~ % curl --silent 'https://query2.finance.yahoo.com/v6/finance/quote?symbols=AAPL' | jq
{
  "quoteResponse": {
    "result": [
      {
        "language": "en-US",
        "region": "US",
        "quoteType": "EQUITY",
        "typeDisp": "Equity",
        "quoteSourceName": "Nasdaq Real Time Price",
        "triggerable": true,
        "customPriceAlertConfidence": "HIGH",
        "currency": "USD",
        "regularMarketChangePercent": -0.36727467,
        "regularMarketPrice": 170.9299,
        "earningsTimestamp": 1683234000,
        "earningsTimestampStart": 1690401600,
        "earningsTimestampEnd": 1690833600,
        "trailingAnnualDividendRate": 0.92,
        "trailingPE": 28.971169,
        "trailingAnnualDividendYield": 0.0053625554,
        "epsTrailingTwelveMonths": 5.9,
        "epsForward": 6.54,
        "epsCurrentYear": 5.97,
        "priceEpsCurrentYear": 28.631475,
        "sharesOutstanding": 15728700416,
        "bookValue": 3.953,
        "fiftyDayAverage": 165.4568,
        "fiftyDayAverageChange": 5.4730988,
        "fiftyDayAverageChangePercent": 0.03307872,
        "twoHundredDayAverage": 152.2147,
        "twoHundredDayAverageChange": 18.715195,
        "twoHundredDayAverageChangePercent": 0.1229526,
        "marketCap": 2688505085952,
        "forwardPE": 26.13607,
        "priceToBook": 43.24055,
        "sourceInterval": 15,
        "exchangeDataDelayedBy": 0,
        "averageAnalystRating": "2.0 - Buy",
        "tradeable": false,
        "cryptoTradeable": false,
        "marketState": "REGULAR",
        "firstTradeDateMilliseconds": 345479400000,
        "priceHint": 2,
        "exchange": "NMS",
        "shortName": "Apple Inc.",
        "longName": "Apple Inc.",
        "messageBoardId": "finmb_24937",
        "exchangeTimezoneName": "America/New_York",
        "exchangeTimezoneShortName": "EDT",
        "gmtOffSetMilliseconds": -14400000,
        "market": "us_market",
        "esgPopulated": false,
        "regularMarketChange": -0.63009644,
        "regularMarketTime": 1684943705,
        "regularMarketDayHigh": 172.27,
        "regularMarketDayRange": "170.765 - 172.27",
        "regularMarketDayLow": 170.765,
        "regularMarketVolume": 17600500,
        "regularMarketPreviousClose": 171.56,
        "bid": 171.05,
        "ask": 171.02,
        "bidSize": 9,
        "askSize": 8,
        "fullExchangeName": "NasdaqGS",
        "financialCurrency": "USD",
        "regularMarketOpen": 171.09,
        "averageDailyVolume3Month": 58180350,
        "averageDailyVolume10Day": 50160350,
        "fiftyTwoWeekLowChange": 46.759903,
        "fiftyTwoWeekLowChangePercent": 0.37657973,
        "fiftyTwoWeekRange": "124.17 - 176.39",
        "fiftyTwoWeekHighChange": -5.4600983,
        "fiftyTwoWeekHighChangePercent": -0.030954693,
        "fiftyTwoWeekLow": 124.17,
        "fiftyTwoWeekHigh": 176.39,
        "dividendDate": 1684368000,
        "displayName": "Apple",
        "symbol": "AAPL"
      }
    ],
    "error": null
  }
}
```

**Comment by nevivurn** [comment]
I'm affected by this too, maybe Yahoo just rolled out this change?

```console
$ curl -i 'https://query2.finance.yahoo.com/v6/finance/quote?symbols=AAPL'
HTTP/2 404 
content-type: application/json;charset=utf-8
y-rid: 6i71piti6sgmv
x-yahoo-request-id: 6i71piti6sgmv
x-request-id: 290854a9-8c9f-40cc-ac99-08b05e3d0511
content-length: 91
x-envoy-upstream-service-time: 1
date: Wed, 24 May 2023 17:01:19 GMT
server: ATS
x-envoy-decorator-operation: finance-quote-api--mtls-production-sg3.finance-k8s.svc.yahoo.local:4080/*
cache-control: max-age=0, private
expires: -1
age: 0
strict-transport-security: max-age=31536000
referrer-policy: no-referrer-when-downgrade
x-frame-options: SAMEORIGIN
expect-ct: max-age=31536000, report-uri="http://csp.yahoo.com/beacon/csp?src=yahoocom-expect-ct-report-only"
x-xss-protection: 1; mode=block
x-content-type-options: nosniff

{"finance":{"result":null,"error":{"code":"Not Found","description":"HTTP 404 Not Found"}}}
```

**Comment by bpschuck** [comment]
Please, no "me too" messages - this issue is being watched for consistent failures.
Thank you.

**Comment by bpschuck** [comment]
I've noticed an occasional 404 code. Usually successful when immediately trying the curl command again. The 404 status code is different from the 401 "Not Authorized" received from the v7 URL.

@vincentl - What do you think about adding a single retry in the YahooJSON.pm modules (there is a new CurrencyRates module) if the first fetch attempt returns a 404? Yeah, it's a kludge, but quicker than parsing different JSON from the v10/v11 Yahoo URLs.

We may have to change to screen scraping the finance.yahoo.com/quote/... web page. Like others have voiced, I'm concerned Yahoo will start blocking access to all the https://query2.finance.yahoo.com/v? API/URLs. I suspect these were not meant for direct access from the internet at large, but only for building the web pages.

**Comment by bpschuck** [comment]
I'm now starting to see consistent failures.

Looks like a more involved re-write of the Yahoo module is required. Either to parse the `https://query2.finance.yahoo.com/v11/finance/quoteSummary/...` output or a web scrape as mentioned previously. Unfortunately I may not have a lot of free time to contribute given the non-trivial nature of the change required.

Would be nice if @vincentl maybe has time. Otherwise, hopefully someone else can step up and contribute.

Thank you.

**Comment by fabrica64** [comment]
[YahooJSON.pm.zip](https://github.com/finance-quote/finance-quote/files/11560351/YahooJSON.pm.zip)

YahooJSON.pm version using https://query2.finance.yahoo.com/v10/finance/quoteSummary/AAPL?modules=price

**Comment by bpschuck** [comment]
Thanks, but the v10 and v11 URLs can have multiple modules. Was also hoping to get other financial data that was available from the v6/v7 URLs. eps, pe, high, low, close, 52 week high and low, etc.

**Comment by fellen** [comment]
On Gnucash-user Carsten mentioned Yahoo's documentation:
[ttps://developer.yahoo.com/sign-in-with-yahoo/#python-step-one](https://developer.yahoo.com/sign-in-with-yahoo/#python-step-one)

**Comment by bpschuck** [comment]
@fellen People are making an assumption that the APIs referred to on the Yahoo developer page are the various URLs used on Yahoo's finance pages. But look at https://developer.yahoo.com/api/ and one only sees a few APIs that have nothing to do with stock market data. 

If the URLs used in the finance pages were those APIs, you would think the https://developer.yahoo.com/api/ would point to a section documenting all the https://query1.finance.yahoo.com/vXX APIs. Call me a skeptic, but I'm going to guess that the API's accessible after setting up OAuth are not for the financial data.

**Comment by deck926** [comment]
Is it possible to concatenate multiple symbols now using https://query2.finance.yahoo.com/v10/finance/quoteSummary/ ??

**Comment by fabrica64** [comment]
> Thanks, but the v10 and v11 URLs can have multiple modules. Was also hoping to get other financial data that was available from the v6/v7 URLs. eps, pe, high, low, close, 52 week high and low, etc.

I updated YahooJSON.pm including additional modules ("price", "summaryDetail" and "defaultKeyStatistics" to get all the values. The only one I've not found a direct reference is "epsTrailingTwelveMonths". I mapped to "trailingEps" in "defaultKeyStatistics" module.

[YahooJSON.pm.zip](https://github.com/finance-quote/finance-quote/files/11565730/YahooJSON.pm.zip)

Reference URL: https://query2.finance.yahoo.com/v11/finance/quoteSummary/AAPL?modules=price,summaryDetail,defaultKeyStatistics

**Comment by Murugan-CL** [comment]
> [YahooJSON.pm.zip](https://github.com/finance-quote/finance-quote/files/11560351/YahooJSON.pm.zip)
> 
> YahooJSON.pm version using https://query2.finance.yahoo.com/v10/finance/quoteSummary/AAPL?modules=price

Since my usage is more related to closing price, this program works perfectly.

**Comment by bpschuck** [comment]
Thanks. I already had a bunch of those noted in https://github.com/finance-quote/finance-quote/discussions/274#discussioncomment-5984994. I think you are correct, "trailingEPS" in the JSON is the "EPS (TTM)" value noted for a security when viewing in the browser. TTM = Trailing 12 Month.
Awesome though, thanks a bunch.

**Comment by bpschuck** [comment]
@Murugan-CL - same already done by @fabrica64 above. Then I asked for getting a few more of the fields that the v6/v7 URLs returned.

**Comment by bpschuck** [comment]
@deck926 - Not exactly sure what you mean. I'm guessing to be able to fetch data for multiple stocks with one web fetch? The modules are already capable of returning data for multiple symbols in a single call.
But I tried a few different variations of passing multiple symbols to the Yahoo URL and none worked.

**Comment by bpschuck** [comment]
@fabrica64 - I'm assuming you're not familiar with creating and submitting git pull requests? If you are, please go ahead. Otherwise I may not be able to get to it until after the holiday weekend here in the US.
Thanks.

**Comment by fabrica64** [comment]
@bpschuck - I created a pull request, hopefully in the right way :-)

**Comment by bpschuck** [comment]
@fabrica64 - Good enough, I just need to tweak a few other files for housekeeping.
Thanks a bunch!

**Comment by bpschuck** [comment]
@fabrica - There is also a currency module, CurrencyRates/YahooJSON.pm. It would be greatly appreciated if that could also be modified to use the v10 or v11 URL.
Thanks.
