### ISSUE TITLE
Gnucash quote greyed out - Finance::Quote version

### ISSUE THREAD

**Issue by mydogonfire** [finance-quote/finance-quote#283]
It seems like gnucash quote button greyed out when the Finance::Quote version is 1.55. I installed gnucash on a different computer and the version is 1.5402. it works fine. Perhaps the gnucash 5.1 does not support Finance::Quote 1.55?

Thanks.

**Comment by bpschuck** [comment]
That would be a GnuCash question. While GnuCash uses F::Q, it is not the only consumer of the Finance::Quote Perl module.
