### ISSUE TITLE
Finance::Quote fails to update to V 1.55, on Windows 10 

### ISSUE THREAD

**Issue by blitz94** [finance-quote/finance-quote#286]
I am trying to update Finance::Quote on my Windows 10 computer.

Current version of Finance::Quote is 
C:\Program Files (x86)\gnucash\bin>gnucash-cli -Q info
Found Finance::Quote version 1.47.

I ran: cpan -i Finance::Quote

But, Finance::Quote remained at 1.47.

**Comment by bpschuck** [comment]
Sorry but this is more of a Perl configuration/install issue than it is an issue with Finance::Quote. Suggest you install/update Finance::Quote using the tool provided by GnuCash and not CPAN.
