### ISSUE TITLE
Perl::Critic failure - Code before strictures

### ISSUE THREAD

**Issue by szabgab** [finance-quote/finance-quote#290]
As I was setting up GitHub Actions to run the tests I encountered a test failure:

```
#   Failed test 'Test::Perl::Critic for "blib/lib/Finance/Quote/TreasuryDirect.pm"'
#   at /opt/hostedtoolcache/perl/5.36.1/x64/lib/site_perl/5.36.1/Test/Perl/Critic.pm line 121.
# 
#   Code before strictures are enabled at line 22, column 1.  See page 429 of PBP.  (Severity: 5)

#   Failed test 'Test::Perl::Critic for "blib/lib/Finance/Quote/TwelveData.pm"'
#   at /opt/hostedtoolcache/perl/5.36.1/x64/lib/site_perl/5.36.1/Test/Perl/Critic.pm line 121.
# 
#   Code before strictures are enabled at line 21, column 28.  See page 429 of PBP.  (Severity: 5)
t/04-critic.t .............. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 2/54 subtests 

#   Failed test 'Data::Dumper should not be loaded'
#   at t/05-data-dumper.t line 20.
# Looks like you failed 1 test of 1.
```

For the full log visit https://github.com/szabgab/finance-quote/actions/runs/5120630743/jobs/9207368469#step:7:78

**Comment by szabgab** [comment]
Sure, you can also specifically mark those two modules to disregard this specific violation, but in this case I think the better solution would be to move the use strict statement right after the `package` statement. I don't think there is any need for `require 5.004;` in https://github.com/finance-quote/finance-quote/blob/master/lib/Finance/Quote/TreasuryDirect.pm

same with  https://github.com/finance-quote/finance-quote/blob/master/lib/Finance/Quote/TwelveData.pm

**Comment by bpschuck** [comment]
On 5/30/23 12:49 PM, Gábor Szabó wrote:

> Sure, you can also specifically mark those two modules to disregard this 
> specific violation, but in this case I think the better solution would 
> be to move the use strict statement right after the |package| statement. 
> I don't think there is any need for |require 5.004;| in 

Yes, I know what the fix is. But unless this affect many other users, 
that fix will be in the next release.
