### ISSUE TITLE
Lots of warnings and errors in tests ONLINE_TEST is enabled

### ISSUE THREAD

**Issue by szabgab** [finance-quote/finance-quote#291]
These are just some of the errors:

```
Error: WARNING: [cmp] Arguments must be valid dates: date1 at t/aex.t line 32.
Error: Use of uninitialized value in numeric eq (==) at t/aex.t line 32.
Error: Use of uninitialized value in concatenation (.) or string at t/aex.t line 45.
Error: Use of uninitialized value $x in pattern match (m//) at /opt/hostedtoolcache/perl/5.36.1/x64/lib/site_perl/5.36.1/x86_64-linux/Date/Simple.pm line 132.
Error: Use of uninitialized value $x in pattern match (m//) at /opt/hostedtoolcache/perl/5.36.1/x64/lib/site_perl/5.36.1/x86_64-linux/Date/Simple.pm line 132.
Error: Can't call method "isa" on an undefined value at /opt/hostedtoolcache/perl/5.36.1/x64/lib/site_perl/5.36.1/Date/Range.pm line 123.
```

See all the results here:  https://github.com/szabgab/finance-quote/actions/runs/5120763640/jobs/9207664018#step:7:80

**Comment by bpschuck** [comment]
This a known issue. Closing issue, many of the modules have not been touched in years. We have been working on removing deprecated modules and fixing the tests over time.

**Comment by szabgab** [comment]
Wouldn't it be better to keep this open so everyone would be able to see that these are known issues and maybe even refer to this issue when they fix some of those?

**Comment by bpschuck** [comment]
Sort of, but I am kind of OCD about issues that will probably be open for a while. Most of the F::Q users are GnuCash users who only need one or two of the most used Modules.
