### ISSUE TITLE
YahooJson returning 404 not found

### ISSUE THREAD

**Issue by bentziaxl** [finance-quote/finance-quote#318]
https://query2.finance.yahoo.com/v11/finance/quoteSummary/APPL?modules=price,summaryDetail,defaultKeyStatistics

output:
{"finance":{"result":null,"error":{"code":"Not Found","description":"HTTP 404 Not Found"}}}

**Comment by bpschuck** [comment]
Probably the last nail in the coffin for YahooJSON. The module will likely be removed in the next Finance::Quote release unless someone can identify another finance.yahoo.com api that returns JSON. Already some reports posted to another issue which becomes a red herring if access is completely denied.

Please, no "me too" comments. 

Sorry, but we have no control over what Yahoo chooses to allow access to.

**Comment by khorton** [comment]
FWIW, the LibreOffice [Financials-Extension](https://github.com/cmallwitz/Financials-Extension) still manages to scrap data from Yahoo, as of a few minutes ago.  Maybe whatever trick they are using in their Python code can be replicated in Perl

**Comment by jeckersb** [comment]
I see the webpage calls out to the chart API which appears to have at least some of the information, most notably current price and previous close.  I'm not familiar enough with the code to know what else (if anything) would be required.  Hopefully it's helpful.

https://query1.finance.yahoo.com/v8/finance/chart/AAPL

```
$ curl -s https://query1.finance.yahoo.com/v8/finance/chart/AAPL | jq .chart.result[0].meta
{
  "currency": "USD",
  "symbol": "AAPL",
  "exchangeName": "NMS",
  "instrumentType": "EQUITY",
  "firstTradeDate": 345479400,
  "regularMarketTime": 1689344613,
  "gmtoffset": -14400,
  "timezone": "EDT",
  "exchangeTimezoneName": "America/New_York",
  "regularMarketPrice": 191.105,
  "chartPreviousClose": 190.54,
  "previousClose": 190.54,
  "scale": 3,
  "priceHint": 2,
  "currentTradingPeriod": {
    "pre": {
      "timezone": "EDT",
      "start": 1689321600,
      "end": 1689341400,
      "gmtoffset": -14400
    },
    "regular": {
      "timezone": "EDT",
      "start": 1689341400,
      "end": 1689364800,
      "gmtoffset": -14400
    },
    "post": {
      "timezone": "EDT",
      "start": 1689364800,
      "end": 1689379200,
      "gmtoffset": -14400
    }
  },
  "tradingPeriods": [
    [
      {
        "timezone": "EDT",
        "start": 1689341400,
        "end": 1689364800,
        "gmtoffset": -14400
      }
    ]
  ],
  "dataGranularity": "1m",
  "range": "1d",
  "validRanges": [
    "1d",
    "5d",
    "1mo",
    "3mo",
    "6mo",
    "1y",
    "2y",
    "5y",
    "10y",
    "ytd",
    "max"
  ]
}
```

**Comment by bpschuck** [comment]
I also discovered either of these will work (hostname can be query2 or query1).

`https://query2.finance.yahoo.com/v11/finance/quoteSummary/?symbol=AAPL&modules=price,summaryDetail,defaultKeyStatistics`

or

`https://query2.finance.yahoo.com/v10/finance/quoteSummary/?symbol=AAPL&modules=price,summaryDetail,defaultKeyStatistics`

While waiting for a new release to be pushed to CPAN, in `YahooJSON.pm` change the `$YIND_URL_HEAD` and `$YIND_URL_TAIL` declarations to:

```
my $YIND_URL_HEAD = 'https://query2.finance.yahoo.com/v11/finance/quoteSummary/?symbol=';
my $YIND_URL_TAIL = '&modules=price,summaryDetail,defaultKeyStatistics';
```

Thanks.
