### ISSUE TITLE
Finance::Quote is intentionally leaking information about its users to a third-party server

### ISSUE THREAD

**Issue by s7eph4n** [finance-quote/finance-quote#327]
Since #310 Finance::Quote is leaking information about it's users to a third-party server.
This is not documented anywhere and there is no opt-out.

This happens over an unprotected HTTP connection.
It's blocking each fetch for up to 10 seconds.

Please remove this behavior (or at the very least make it opt-in).

**Comment by bpschuck** [comment]
It's a temporary way of looking at usage per module/method. Other than that and source IP which is always part of web logs, no PIN is passed.

**Comment by s7eph4n** [comment]
You are arguing that it's not a big deal. Well, in that case you might as well properly document it and provide an opt-in mechanism.
Surely users will not see a problem providing their data.
