### ISSUE TITLE
BSEIndia.pm inserts extra string into return value on retrieval failure

### ISSUE THREAD

**Issue by jralls** [finance-quote/finance-quote#335]
If a symbol isn't found the BSE parser [inserts an invalid string into the return value](
https://github.com/finance-quote/finance-quote/blob/0e75f358235ab3ab8a8e09153e1786a0282c6f62/lib/Finance/Quote/BSEIndia.pm#L128) , crashing attempts to parse the value as JSON.

**Comment by bpschuck** [comment]
Thanks @jralls. While the fix did not make it into v1.58, you can download and install BPSCHUCK/Finance-Quote-1.58_01.tar.gz from CPAN for testing/verification. It also has what I hope is a fix for TSP. It was not returning the hash if the GET failed or if the body of the response produced a CSV file.
