### ISSUE TITLE
Fidelity.pm Not Working

### ISSUE THREAD

**Issue by bpschuck** [finance-quote/finance-quote#346]
Fidelity website changed. The URL `https://fundresearch.fidelity.com/mutual-funds/fidelity-funds-daily-pricing-yields/download` no longer produces the CSV data the Fidelity.pm module parses.

Mark the module as failing and remove or possibly rewrite the module to utilize `https://quotes.fidelity.com/webxpress/ia_basic_quote_frameset.phtml?QUOTE_TYPE=R&SID_VALUE_ID=<symbol>&type=sq-NavBar` (Replace `<symbol>` with desired fund ticker).

**Comment by bpschuck** [comment]
Fidelity.pm is temporarily removed from Quote.pm for v1.59. If fixed by v1.60 it will be restored, otherwise permanently removed.

**Comment by titanofold** [comment]
> `https://quotes.fidelity.com/webxpress/ia_basic_quote_frameset.phtml?QUOTE_TYPE=R&SID_VALUE_ID=<symbol>&type=sq-NavBar`

This is giving a 301 to https://digital.fidelity.com/prgw/digital/research/

**Comment by bpschuck** [comment]
As stated previously, for the time being the Fidelity.pm module is being disabled in F::Q.
