### ISSUE TITLE
`XETRA.pm` no longer working

### ISSUE THREAD

**Issue by di-br** [finance-quote/finance-quote#350]
I'm using v1.54 and believe sometime this week using `xetra` as source stopped working. I'm getting an error
```sh
 Can't call method "look_down" on an undefined value at /usr/share/perl5/Finance/Quote/XETRA.pm line 66
```
I don't speak Perl, but my best guess is that the used website changed a class name (though I've never been to the website before or was even aware which site it's using).

Replacing
```perl
   my $lastvalue = $tree->look_down('class'=>'si_inner_content_box');
```
with
```perl
   my $lastvalue = $tree->look_down('class'=>'contentwrapper');
```
seems to fix the issue and I can obtain rates again.

**Comment by bpschuck** [comment]
@di-br,
Thank you for the report. While the current release of F::Q, 1.58, does not address this issue, the team prefers that issues are reported against the current release. Users should update Finance::Quote and confirm the issue exists in the current release before submitting an issue to GitHub.
Thank you.

**Comment by bpschuck** [comment]
@di-br 
I see you closed this. Should I understand that to mean that after updating F::Q to v1.58 the issue no longer exists?

**Comment by di-br** [comment]
I did not attempt an update and prefer to stay with whatever my package manager provides. As far as I can tell, the line I _think_ may be problematic is still in the latest version. I did see errors with a command like
```sh
gnc-fq-dump -v xetra "US5949181045"
```
but only really use F::Q via `gnucash`.

**Comment by bpschuck** [comment]
Reopening. After some quick checking, the required changes look to be much more than the one line @di-br has pointed out.
@mumpitzstuff - Having made the last fix to XETRA.pm it would be appreciated if you could please look at updating the module to account for the recent changes? Thanks!
