### ISSUE TITLE
Get Quotes Throws Error 

### ISSUE THREAD

**Issue by biomade** [finance-quote/finance-quote#351]
I am using a Windows 11 machine with
GnuCash ver. 5.4
Build ID: git 5.4-109-g1d8c525afc+(2023-11-24) 
Finance::Quote: 1.58

I have run "Install Online Price Retrieval for GnuCash"
I have requested and added the AlphaVantage API Key to the preferences dialog box as well as the system environment variables.

I set up my stocks and mutual funds in the Security Editoor. Ony one stock in my portfolio, via the Security Editor to configured to automatically retrieve quotes
<img width="320" alt="Screenshot 2023-11-25 150839" src="https://github.com/finance-quote/finance-quote/assets/26169735/69b0345e-7c54-47f0-a1b1-5f973f702083">

In the Price DB dialog box I clicked the button to Get Quotes and a  Perl window opens and then I get an error message in a dialog box.

I also ran this command from a CMD window (as admin) 
>gnucash-cli.exe --quotes get file://C:/Users/xxx/xxx/FinanceBudget/gnucash/Kern.gnucash

Found Finance::Quote version 1.58.
* 15:04:40 ERROR <gnc.price-quotes> [parse_quotesource_error()] Unrecognized Finance::Quote Error Can't use an undefined value as a HASH reference at C:/Strawberry/perl/site/lib/Finance/Quote/AlphaVantage.pm line 261.
Price retrieval failed: Unrecognized Finance::Quote Error: Can't use an undefined value as a HASH reference at C:/Strawberry/perl/site/lib/Finance/Quote/AlphaVantage.pm line 261.

This is the same as the dialog box from within GnuCash

IF I run the AlphaVantage query below via my browser:
https://www.alphavantage.co/query?function=SYMBOL_SEARCH&keywords=RTX&apikey=xxx
I do get a response back in the browser

AND...if I run this command in a CMD window
>gnucash-cli --quotes dump xxx NYSE:RTX
I get the following response:
Finance::Quote retrieval failed with error Failed to parse result returned by Finance::Quote.
Error message:
<unspecified file>(1): expected value
Result:

**Comment by bpschuck** [comment]
Is that a space in the symbol `NYSE: RTX`? The symbols should not contain spaces.

If removing the space does not correct your issue, please try to test Finance::Quote using the example script supplied in the package. You may have to look for this, but on my Windows 10 desktop CPAN will keep recent build source in `C:\Users\xxxxx\AppData\Local\.cpan\build\`. The Finance::Quote source is found at `C:\Users\xxxxx\AppData\Local\.cpan\build\Finance-Quote-1.58-0`.

```
cd C:\Users\xxxxx\AppData\Local\.cpan\build\Finance-Quote-1.58-0
set ALPHAVANTAGE_API_KEY=foobar123
perl Examples\stockdump.pl alphavantage AAPL
$VAR1 = {
          'AAPL∟currency' => 'USD',
          'AAPL∟p_change' => '-0.7004',
          'AAPL∟isodate' => '2023-11-24',
          'AAPL∟method' => 'alphavantage',
          'AAPL∟open' => '190.8700',
          'AAPL∟net' => '-1.3400',
          'AAPL∟success' => 1,
          'AAPL∟currency_set_by_fq' => 1,
          'AAPL∟high' => '190.9000',
          'AAPL∟date' => '11/24/2023',
          'AAPL∟volume' => '24048344',
          'AAPL∟last' => '189.9700',
          'AAPL∟symbol' => 'AAPL',
          'AAPL∟close' => '191.3100',
          'AAPL∟low' => '189.2500'
        };
```
This tests F::Q independent of GnuCash. 

If you have another Perl installed, such as Active State's Perl, this can also create issues as libraries (aka modules) meant for one could be getting used by the other.

**Comment by biomade** [comment]
Bruce.
I ran the test script you suggested and it worked. I tried "RTX" and "NYSE:RTX" and they both worked
In the screen shot, yes there is/was a space. I removed the space; saved and tried the Get Quotes and I still get the same error.

**Comment by bpschuck** [comment]
@biomade,
If the test script worked, than this is **not** an issue with Finance::Quote.
