### ISSUE TITLE
GoogleWeb.pm does not support BATS exchange

### ISSUE THREAD

**Issue by RichardCory** [finance-quote/finance-quote#355]
Using 1.58 of Finance::Quote

`gnucash-cli --quotes dump googleweb esml`

does not succeed. I have tracked the issue to line 90 of GoogleWeb.pm

`$taglink = $tree->look_down(_tag => 'a', href => qr!^./quote/$ucstock:(MUTF|NYSE|NASDAQ|NYSEAMERICAN)!);`

(In the version included with 1.58, the MUTF criterion isn't actually present. The line above is taken from the current version on github). The issue can be fixed simply by changing the statement to

`$taglink = $tree->look_down(_tag => 'a', href => qr!^./quote/$ucstock:(MUTF|NYSE|NASDAQ|NYSEAMERICAN|BATS)!);`

I would try submitting this myself, but I don't currently have a working local environment.

**Comment by bpschuck** [comment]
Not being familiar with what securities or funds are traded on BATS, an example or two would be appreciated for testing and possible inclusion into the googleweb.t test script.

**Comment by RichardCory** [comment]
> Not being familiar with what securities or funds are traded on BATS, an example or two would be appreciated for testing and possible inclusion into the googleweb.t test script.

I did provide an example in the command line above, of ESML (iShares ESG Aware MSCI USA Small-Cap ETF, https://www.google.com/finance/quote/ESML:BATS).

Another example is NULC (Nuveen ESG Large-Cap ETF, https://www.google.com/finance/quote/NULC:BATS)

Many more can be found at https://www.marketbeat.com/stocks/BATS/
