### ISSUE TITLE
Bloomberg Parse Error

### ISSUE THREAD

**Issue by 3aboooody56** [finance-quote/finance-quote#360]
Hello, 

The Bloomberg module has been returning parse errors lately. From what I found, there are two issues: One has to do with the encoding/decoding of the HTML page, and the other is a parsing error.

I have found that removing line 42 in the module solves the encoding/decoding issue: `'Accept-Encoding' => 'br',`

As for the parsing issue, changing line 58 to the following solves it: 
`my $date  = $tree->look_down(_tag=>'span', 'class'=>qr/^marketLastUpdate_exchangeDelay___PZEn/)->right();`

**Comment by bpschuck** [comment]
@3aboooody56
Thanks for the info.
It would be appreciated if you could create a pull request. Please note that we ask to update "Changes" and "Modules-README.yml" to save us some housecleaning time when preparing to push a release to CPAN. As always, check for a clean execution of the test script and update any symbols that are no longer traded.

**Comment by 3aboooody56** [comment]
@bpschuck

The changes I mentioned earlier partially fix the Bloomberg module. After testing the changes, the module fails to retrieve the prices for US / USD-based stocks (works for other stocks). The HTML document/webpage is different for US stocks - at least the HTML elements that contain the stock price are different. I tried fixing this by having two separate `look_down` method calls for the two cases.

But I am currently running into another issue with this other HTML webpage for US stocks where the HTML page content that is pulled by the module (Opened as a text file) is missing the price or at least where it should be:

<div class="currentPrice_currentPriceContainer__nC8vw">
   <div class="priceDelta_price__Acvmw">
      <span class="priceDelta_black__KE45q"></span>

When opening that same HTML page content that was pulled by the module in a browser, the price shows up in the HTML content as follows:

<div class="currentPrice_currentPriceContainer__nC8vw">
   <div class="priceDelta_price__Acvmw">
      <span class="priceDelta_black__KE45q">141.18</span>

This was the case for GOOGL:US.

Would appreciate any insight as to why this happens and what can be done about it. Thanks.

**Comment by bpschuck** [comment]
@3aboooody56 
Sorry, but I currently don't have the time to troubleshoot the module. Apparently Bloomberg has made changes to the structure of the web pages that break the parsing logic in the module. There is a similar issue with the Fidelity.pm that was discovered 6 months ago.

**Comment by pghmcfc** [comment]
@bpschuck
> Would appreciate any insight as to why this happens and what can be done about it. Thanks.

Looks like it fills in the price using some javascript. Came across the exact same issue when looking at this yesterday. Fortunately, there is a giant blob of JSON embedded as a script in the page, from which it is easy to extract the data. PR incoming soon.

**Comment by 3aboooody56** [comment]
Thanks for the fix.

As a GnuCash user, how can I have it use a modified version of F: :Q instead of having to wait for the next release?

**Comment by pghmcfc** [comment]
@3aboooody56 
 * Go to the pull request at #362
 * Select the "Files changed" tab
 * In the code tree view on the left hand side, click on the file of interest, "Bloomberg.pm"
 * In the main part of the window, from the menu ("...") for that file, select "View file"
 * When the modified file is shown, click the "Download raw file" option (to the right of the "Raw" button) 
 * Replace the file "Bloomberg.pm" in your current installation with the one you just downloaded
 
That should do it.

**Comment by 3aboooody56** [comment]
Thanks, that worked. Took me a bit to find the version of Perl and F::Q that GnuCash was using.

**Comment by bpschuck** [comment]
> Thanks, that worked. Took me a bit to find the version of Perl and F::Q that GnuCash was using.

@3aboooody56 

That is typically why I don't typically even attempt to answer questions about installing individual modules. For those with experience in Perl it is simple. But it is possible to find multiple instances of F::Q installed.
