### ISSUE TITLE
MacOS Sonoma Upgrade Finance Quote Not Working

### ISSUE THREAD

**Issue by lodenrogue** [finance-quote/finance-quote#365]
After upgrading my Mac OS to Sonoma 14.4.1 I am facing this issue when trying to use Finance::Quote with GnuCash. It seems GnuCash can't find Finance::Quote or thinks it's not installed properly.

"Warning: Finance::Quote not installed properly"

I tried running the gnc-fq-update script but that didn't fix it.

I know this is not a GnuCash repository but I was hoping there was someone who faced a similar issue with Sonoma and found a fix.

**Comment by crowedavid** [comment]
i had the same issue and had to start fresh with my perl libraries.  i use the local::lib perl library install method so it was easy to remove ~/perl5 and ~/.cpan and start over - you may need to do surgery where your perl installed the libs.

the Gnucash online docs has some guidance:

https://wiki.gnucash.org/wiki/Online_Quotes#Installing_Finance::Quote_on_macOS

using one of the universal binary options described there.

**Comment by lodenrogue** [comment]
> i had the same issue and had to start fresh with my perl libraries. i use the local::lib perl library install method so it was easy to remove ~/perl5 and ~/.cpan and start over - you may need to do surgery where your perl installed the libs.
> 
> the Gnucash online docs has some guidance:
> 
> https://wiki.gnucash.org/wiki/Online_Quotes#Installing_Finance::Quote_on_macOS
> 
> using one of the universal binary options described there.

Thanks David. I tried this but it didn't resolve the issue.

**Comment by bpschuck** [comment]
Unfortunately this is more of an OSX issue than a Finance::Quote issue. Sorry.

**Comment by lodenrogue** [comment]
@bpschuck So this means anyone with a Mac can't use Finance::Quote if they have an up to date OS? Or is the issue with GnuCash on MacOS?

**Comment by bpschuck** [comment]
F::Q can be used, but recent versions of OSX (especially OSX on M1 and M2 chips) have made installation less than trivial. In a nutshell, installing *any* Perl module that requires access to C library functions and compiling (what Perl calls XS or XSUB extensions). Search the gnucash-user list email archives, you are not the first to experience the headache.
