### ISSUE TITLE
YahooWeb failing with "Header line too long" error

### ISSUE THREAD

**Issue by fabrica64** [finance-quote/finance-quote#377]
```
$ /Applications/Gnucash.app/Contents/MacOS/gnucash-cli --quotes dump yahooweb AAPL
Application Path /Applications/Gnucash.app/Contents/MacOS/gnucash-cli
Finance::Quote reported a failure for symbol AAPL: 500 Header line too long (limit is 8192)
```
I don't know if it is just for me but from April 15 I get this error trying to use YahooWeb

MacOS 14.4.1 (Apple Silicon)
Perl 5.38.2
Finance::Quote 1.60

It happens also in Windows 10 with Strawberry Perl 5.28.1 and Finance::Quote 1.59

**Comment by carlosala** [comment]
Yep, I can reproduce as well. `yahoo_json` is broken as well as reported in #373

**Comment by zinglo** [comment]
After upgrading to 1.60... If I look at the installed code vs the recent changes... I still see a bit of the old code.  For example, the $YIND_URL_HEAD seems to still be V11, while the $VERSION is 1.60.  I still get the same 401 unauthorized as I was getting last week.

our $VERSION = '1.60'; # VERSION

my $YIND_URL_HEAD = 'https://query2.finance.yahoo.com/v11/finance/quoteSummary/?symbols=';
my $YIND_URL_TAIL = '&modules=price,summaryDetail,defaultKeyStatistics';

Built with cpan2deb on Ubuntu 22.04.4 LTS

**Comment by andershm** [comment]
I can reproduce both problems:
`% /Applications/Gnucash.app/Contents/MacOS/gnucash-cli --quotes dump yahoo_json AAPL
Application Path /Applications/Gnucash.app/Contents/MacOS/gnucash-cli
Finance::Quote reported a failure for symbol AAPL: Error retrieving quote for AAPL. Attempt to fetch the URL https://query2.finance.yahoo.com/v11/finance/quoteSummary/?symbols=AAPL&crumb={"finance":{"result":null,"error":{"code":"Unauthorized","description":"Invalid Cookie"}}}&modules=price,summaryDetail,defaultKeyStatistics resulted in HTTP response 401 (Unauthorized)

% /Applications/Gnucash.app/Contents/MacOS/gnucash-cli --quotes dump yahooweb AAPL
Application Path /Applications/Gnucash.app/Contents/MacOS/gnucash-cli
Finance::Quote reported a failure for symbol AAPL: 500 Header line too long (limit is 8192)`

**Comment by bpschuck** [comment]
@fabrica64 

> I don't know if it is just for me but from April 15 I get this error trying to use YahooWeb

I believe Yahoo may have changed the format which affect the various regex screen scraping that the YahooWeb module uses. 

Thanks.

**Comment by bpschuck** [comment]
Adding this as notes for when I (or someone else) works on pull request.

I can fix the "500 Header line too long (limit is 8192)" error by adding

    use LWP::Protocol::http;
    push(@LWP::Protocol::http::EXTRA_SOCK_OPTS, MaxLineLength => 0);
    
near the top of the `YahooWeb.pm` module. BUT, the format of the page returned has also changed. Good news is that it includes JSON which is easier to parse.
