### ISSUE TITLE
Unable to use SIX module from GnuCash

### ISSUE THREAD

**Issue by hhindriks** [finance-quote/finance-quote#380]
Today I installed v1.60 and was trying to use the SIX module to get the current price of UBSG from GnuCash. 
Output of gnucash-cli (translated from German):

```
c:\...>gnucash-cli --quotes dump six UBSG
Finance::Quote fields GnuCash uses::
    symbol: **missing**   <=== required
      date: 04/17/2024    <=== recommended
  currency: USD           <=== required
      last: **missing**   <=\
       nav: **missing**   <=== one of these
     price: **missing**   <=/
```

adding the option _--verbose_ shows that the call is indeed returning data. just not the fields GnuCash is expecting. I have no experience with perl but with the following modifications GnuCash was updating its price db using the module:

- return **symbol** by adding the following line around line 75: 
    `$info{$symbol, 'symbol'}   = $metarow->[$metamap{ValorSymbol}]; `
- return **last** by adding the following line around line 97: 
   `$info{$symbol, 'last'}    = $datarow->[$datamap{ClosingPrice}]   if $datarow->[$datamap{ClosingPrice}];`

the last issue I noted was the returned currency, e.g. USD instead of CHF, this was solved by replacing the line
`$info{$symbol, 'currency'} = $metarow->[$metamap{NominalCurrency}];`
with
`$info{$symbol, 'currency'} = $metarow->[$metamap{TradingBaseCurrency}];`

To investigate the **valorid** was returned as well (line 62):
`$info{$symbol, 'valor'} = $valorid;`

With these modifications all the shares and ETFs I am interested in return the expected quotes. - Thanks for all the work creating and maintaining Finance-Quote!

**Comment by bpschuck** [comment]
The SIX.pm module has probably not been working for a **long** time. Not sure if this will get addressed or if the module will get dropped. Sorry.

**Comment by bpschuck** [comment]
Pre-release v1.60_01 pushed to CPAN.
BPSCHUCK/Finance-Quote-1.60_01.tar.gz
