### ISSUE TITLE
NZX Website Update - NZX Quotes no longer working

### ISSUE THREAD

**Issue by Emporium2184** [finance-quote/finance-quote#401]
NZX website has been updated, as such pulling quotes direct from NZX is no longer possible.

**Comment by bpschuck** [comment]
Thank you for reporting the issue.

**Comment by bpschuck** [comment]
When did you notice this module stopped working? Do you use it often? Are you comfortable using interim releases of F::Q?
Thanks.

**Comment by Emporium2184** [comment]
Bruce,
I use it daily, and happy to use an interim release.  It stopped working Thursday/Friday just gone.




Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bpschuck** [comment]
Try `cpan BPSCHUCK/Finance-Quote-1.62_01.tar.gz`

**Comment by Emporium2184** [comment]
Excellent, thanks for the prompt response and solution.

**Comment by bpschuck** [comment]
This will be closed when PR #402 is merged.
