### ISSUE TITLE
ASX Cleanup

### ISSUE THREAD

**Issue by bpschuck** [finance-quote/finance-quote#404]
The primary URL in ASX.pm, https://www.asx.com.au/asx/1/share/$symbol, is protected from robots and web scraping by Imperva Incapsula. This query fails, and the module consistently reverts to using its alternate URL https://asx.api.markitdigital.com/asx-research/1.0/companies/$symbol/header. This URL returns the following for the symbol ARG:

```
{
  "data": {
    "dateListed": "1963-03-31",
    "displayName": "ARGO INVESTMENTS LIMITED",
    "priceAsk": 8.65,
    "priceBid": 8.6,
    "priceChange": 0,
    "priceChangePercent": 0,
    "priceLast": 8.63,
    "securityType": 1,
    "symbol": "ARG",
    "volume": 238992,
    "xid": "47787",
    "marketCap": 6569520747,
    "statusCode": ""
  }
}
```

No trade date is available. 

Clean up ASX.pm to not bother attempting to use the primary URL. The test script `t/asx.t` needs to changed to remove checks for values no longer available. 

As always, modify `Changes` and `Modules-README.yml` to reflect the changes.

**Comment by bpschuck** [comment]
@goodvibes2 
If you have time to look at this and do some cleanup, that would be awesome.
Thanks.

**Comment by bpschuck** [comment]
Will be removed in v1.64. We've had issues with price data with no date attached.

**Comment by goodvibes2** [comment]
Bruce,

Asx still works for me. Please do not remove. I'd it ever stops working,
then I will have to make time to fix it, but I really don't have any spare
time.

Chris Good

**Comment by bpschuck** [comment]
On 10/20/24 4:21 PM, Chris Good wrote:

> Asx still works for me. Please do not remove. I'd it ever stops working,
> then I will have to make time to fix it, but I really don't have any spare
> time.

You don't mind that the data being returned does not have a date? Which 
means GnuCash will assign the current day, even if the price retrieval 
was done on a weekend or holiday.

Bruce S.

**Comment by goodvibes2** [comment]
Hi Bruce, I would sooner it did have a date, and from memory, I looked at
the data and there was a date that would do, but that's not a stopper for
me. Chris

**Comment by bpschuck** [comment]
On 10/20/24 4:40 PM, Chris Good wrote:

> Hi Bruce, I would sooner it did have a date, and from memory, I looked at
> the data and there was a date that would do, but that's not a stopper for
> me. Chris

Please look at previous comments on the issue. The primary URL no longer 
works, protected by a JS based anti-scraping service/tech called 
Incapsula (see imperva.com). Adding a JS engine to F::Q for normal users 
would be a nightmare to support. The module *always* reverts to the 
alternate URL which only supplies:

     {
       "data": {
         "dateListed": "1963-03-31",
         "displayName": "ARGO INVESTMENTS LIMITED",
         "priceAsk": 8.65,
         "priceBid": 8.6,
         "priceChange": 0,
         "priceChangePercent": 0,
         "priceLast": 8.63,
         "securityType": 1,
         "symbol": "ARG",
         "volume": 238992,
         "xid": "47787",
         "marketCap": 6569520747,
         "statusCode": ""
       }
     }

I'm certain dateListed isn't going to cut it... ;)

Bruce S.

**Comment by bpschuck** [comment]
Just putting this here for later reference.
https://www.marketindex.com.au/asx-listed-companies

**Comment by bpschuck** [comment]
So what are numerics and warrants? Give me the ASX listings for dummies explanation.

**Comment by CleanShed** [comment]
> So what are numerics and warrants? Give me the ASX listings for dummies explanation.

ASX "Warrants" are derivatives and give you the right to buy or sell a nominated underlying security at a particular price sometime in the future.  You might know them as "Options", for example:

[https://www.barchart.com/stocks/quotes/IBM/options?expiration=2024-10-25-w](https://www.barchart.com/stocks/quotes/IBM/options?expiration=2024-10-25-w)

[https://www.asx.com.au/content/dam/asx/investors/investment-options/ASX_Understanding_Warrants_Edition_18.pdf](https://www.asx.com.au/content/dam/asx/investors/investment-options/ASX_Understanding_Warrants_Edition_18.pdf)

I am not sure what you are referring to by "numerics"?

**Comment by CleanShed** [comment]
> Just putting this here for later reference. https://www.marketindex.com.au/asx-listed-companies

That's a nice page but it is protected - here is what I get when I try to grab it:

`<div class="h2"><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div>`

**Comment by bpschuck** [comment]
On 10/22/24 04:09, CleanShed wrote:

>     Just putting this here for later reference.
>     https://www.marketindex.com.au/asx-listed-companies
>     <https://www.marketindex.com.au/asx-listed-companies>

> That's a nice page but it is protected - here is what I get when I try 
> to grab it:

Reference was for confirming symbols in t/asx.t exist.

**Comment by bpschuck** [comment]
On 10/22/24 04:07, CleanShed wrote:

> I am not sure what you are referring to by "numerics"?

In the t/asx.t test script, there is this line

my @numerics   = qw/360 14D A2M XF1/;

I was wondering if something being called a "numeric" had a special 
significance. Or are they just "ordinaries" with digits in the symbol?

**Comment by bpschuck** [comment]
On 10/22/24 04:16, CleanShed wrote:

> @bpschuck <https://github.com/bpschuck> , I agree with @goodvibes2 
> <https://github.com/goodvibes2> , a price without a date (and
> defaulting to the user's system date) is better than no price at all.
> What if we just drop the primary URL altogether?

Apparently everyone who uses ASX hasn't noticed, since the primary URL 
has been failing for quite some time. I'm almost done with fixes.

**Comment by CleanShed** [comment]
> On 10/22/24 04:07, CleanShed wrote: I am not sure what you are referring to by "numerics"?
> In the t/asx.t test script, there is this line my @numerics = qw/360 14D A2M XF1/; I was wondering if something being called a "numeric" had a special significance. Or are they just "ordinaries" with digits in the symbol?

That's correct.

**Comment by bpschuck** [comment]
On 10/22/24 2:54 PM, CleanShed wrote:

>     On 10/22/24 04:07, CleanShed wrote: I am not sure what you are
>     referring to by "numerics"?
>     In the t/asx.t test script, there is this line my @numerics
>     <https://github.com/numerics> = qw/360 14D A2M XF1/; I was wondering
>     if something being called a "numeric" had a special significance. Or
>     are they just "ordinaries" with digits in the symbol?

> That's correct.

Thanks. Since I do not trade or follow the Aussie stock exchange, I 
wondered why they were called out differently in the test script.
