### ISSUE TITLE
Cpan Installation hangs and never finish, module not installed

### ISSUE THREAD

**Issue by arnold-b** [finance-quote/finance-quote#406]
t/00-report-prereqs.t .. #
# Versions for all modules listed in MYMETA.json (including optional ones):
#
# === Configure Requires ===
#
#     Module              Want Have
#     ------------------- ---- ----
#     ExtUtils::MakeMaker 6.78 7.70
#
# === Build Requires ===
#
#     Module              Want Have
#     ------------------- ---- ----
#     ExtUtils::MakeMaker  any 7.70
#
# === Test Requires ===
#
#     Module                Want     Have
#     --------------------- ---- --------
#     ExtUtils::MakeMaker    any     7.70
#     File::Spec             any     3.80
#     Test::Builder::Tester  any 1.302198
#     Test::More            0.65 1.302198
#     overload               any     1.33
#
# === Test Recommends ===
#
#     Module         Want     Have
#     ---------- -------- --------
#     CPAN::Meta 2.120900 2.150010
#
# === Runtime Requires ===
#
#     Module        Want     Have
#     ------------- ---- --------
#     Carp           any     1.52
#     Exporter      5.57     5.78
#     Test::Builder  any 1.302198
#     Try::Tiny     0.07     0.31
#     strict         any     1.12
#     warnings       any     1.51
#
t/00-report-prereqs.t .. ok
t/basic.t .............. ok
t/like-exception.t ..... ok
t/todo.t ............... ok
All tests successful.
Files=4, Tests=18, 31 wallclock secs ( 0.09 usr  1.15 sys +  0.71 cusr  0.21 csys =  2.16 CPU)
Result: PASS
Lockfile removed.

**Comment by bpschuck** [comment]
Not enough details. Likely a localized issue and not a Finance::Quote problem.
Please include

OS details, distribution, release version, etc.
Output of `perl -V`.
Is Gcc, make, and other development tools installed. Needed for CPAN to work.
How was F::Q installed?
