### ISSUE TITLE
BVB Module Not Working

### ISSUE THREAD

**Issue by bpschuck** [finance-quote/finance-quote#409]
The BVB module stopped working. Data is no longer included in body of HTML from the URL https://bvb.ro/FinancialInstruments/Details/FinancialInstrumentsDetails.aspx?s=$symbol
Web pages have been redesigned.

**Comment by bgr22112** [comment]
@bpschuck i have made changes to this module to fetch end of trading day quotes from the historical prices file published by the exchange. Currently testing them out.
