### ISSUE TITLE
OnVista Module not working

### ISSUE THREAD

**Issue by bpschuck** [finance-quote/finance-quote#414]
The OnVista.pm module is not working. Likely due to changes in the HTML returned from `https://www.onvista.de/suche/$stock`.

**Comment by bpschuck** [comment]
@ka-patel,

Do you feel like taking a shot at this one? It is okay if you don't.

**Comment by ka-patel** [comment]
I can look into it…

**Comment by bpschuck** [comment]
> I can look into it…

BTW - When working on existing modules or adding new ones, there is a rework to how labels and methods are presented. Please refer this gist: https://gist.githubusercontent.com/bpschuck/7c19064bccdf903de0977e59647813c4/raw/48041ec7759aabcca44bee35bcbcfe40673a3c82/methodinfo

For examples, these modules currently have this in place:

- Bourso
- FinanceAPI
- StockData

Any questions, please ask.

Thank you.

**Comment by ka-patel** [comment]
Indeed. I saw that update few releases back.

**Comment by bpschuck** [comment]
Nevermind, I am almost ready to submit a PR.
