### ISSUE TITLE
yahoo_json stopped working in July

### ISSUE THREAD

**Issue by jmgomezpoveda** [finance-quote/finance-quote#43]
Trying to get any quote from yahoo_json (which goes to the URL http://finance.yahoo.com/webservice/v1/symbols/$SYMBOLS/quote?format=json), returns "`Not a valid parameter`" error and HTTP Code `406`.

Apparently (http://stackoverflow.com/a/38390559/1816603) a workaround is to set a mobile user agent, like `"Mozilla/5.0 (Linux; Android 6.0.1; MotoG3 Build/MPI24.107-55) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.81 Mobile Safari/537.36"`.

**Comment by ecocode** [comment]
yahoo closed the service
