### ISSUE TITLE
FinanceAPI 'malformed UTF-8 character in JSON string..." error

### ISSUE THREAD

**Issue by crowedavid** [finance-quote/finance-quote#434]
While moving my quotes over to use the new FinanceAPI source in v1.63, I found one bug that appears for one specific fund I hold:

```
xxxx-slab Finance-Quote-1.63-0 • pwd
/Users/xxxx/.cpan/build/Finance-Quote-1.63-0
xxxx-slab Finance-Quote-1.63-0 • FINANCEAPI_API_KEY=XXXXXXXXXXX Examples/stockdump.pl financeapi SWPPX
$VAR1 = {
          'SWPPXerrormsg' => 'malformed UTF-8 character in JSON string, at character offset 248 (before "\\x{fffd} S&P 500 Ind...") at /Users/xxxx/perl5/lib/perl5/Finance/Quote/FinanceAPI.pm line 110.
',
          'SWPPXsuccess' => 0,
          'SWPPXsymbol' => 'SWPPX'
        };
```

doing the same with yahoo_json it shows the following:

```
xxxx-slab Finance-Quote-1.63-0 • Examples/stockdump.pl yahoo_json SWPPX
$VAR1 = {
          'SWPPXname' => "SWPPX (Schwab\x{ae} S&P 500 Index Fund\",)",
          'SWPPXmethod' => 'yahoo_json',
          'SWPPXopen' => undef,
          'SWPPXlast' => '88.4',
          'SWPPXhigh' => undef,
          'SWPPXisodate' => '2024-10-02',
          'SWPPXsuccess' => 1,
          'SWPPXvolume' => undef,
          'SWPPXeps' => undef,
          'SWPPXclose' => '88.380005',
          'SWPPXsymbol' => 'SWPPX',
          'SWPPXdiv_yield' => '1.1767367',
          'SWPPXcurrency' => 'USD',
          'SWPPXexchange' => 'Nasdaq',
          'SWPPXlow' => undef,
          'SWPPXyear_range' => '       63.83 - 89.21',
          'SWPPXtype' => 'MUTUALFUND',
          'SWPPXdate' => '10/02/2024',
          'SWPPXpe' => '28.794395'
        };
```

this appears to be caused by the use of the "®" symbol in the "Schwab® S&P 500 Index Fund" fund name so will probably affect others.

**Comment by bpschuck** [comment]
Thanks.
How comfortable are you with finding and editing the code directly? If you are okay with that:

Find where `Finance::Quote::FinanceAPI` is installed on your system. Edit the file with your preferred editor (vim, emacs, joe, etc). Go to line 99: `my $body    = decode('UTF-8', $reply->content);`. Change it to `my $body    = $reply->content;`

That _should_ fix it. It may be a coupla-few days before I get to making an official fix and pull request.

Bruce S.

**Comment by crowedavid** [comment]
thanks - that worked perfectly.

**Comment by bpschuck** [comment]
> thanks - that worked perfectly.

Not a problem. BTW, I X'd out your API key in the original post. You probably already know, but posting any type of private token, key, etc. anywhere is bad mojo.

**Comment by crowedavid** [comment]
> Not a problem. BTW, I X'd out your API key in the original post. You probably already know, but posting any type of private token, key, etc. anywhere is bad mojo.

ugh - thanks, i did mean to do that and missed it when reediting the markdown. :-(
