### ISSUE TITLE
Cannot follow install instructions - there is no Makefile.PM?

### ISSUE THREAD

**Issue by jusmop** [finance-quote/finance-quote#56]
I cloned the git repository (master) but there is no Makefile.PM.
Can someone point me to it?

**Comment by jusmop** [comment]
OK thanks.

I installed the latest, but I still cannot get stock quotes from within
GnuCash. I changed the quote source from Yahoo to ASX for every stock but
GnuCash reports that all quote requests failed.

I have tested the Finance-Quote stand-alone using a simple perl script and
it works.

How do I check if GnuCash is calling the correct package?

Cheers,
Justin.

**Comment by ecocode** [comment]
jusmop <notifications@github.com> writes:

> OK thanks.
>
> I installed the latest, but I still cannot get stock quotes from within
> GnuCash. I changed the quote source from Yahoo to ASX for every stock but
> GnuCash reports that all quote requests failed.

If you want to change to the latest module alphavantage, the correct
source should be alphavantage, not ASX...

>
> I have tested the Finance-Quote stand-alone using a simple perl script and
> it works.
>
> How do I check if GnuCash is calling the correct package?

Can't help with that as I don't use GnuCash.  Please ask this question
on the GnuCash user list.

best
--
erik colson

**Comment by jusmop** [comment]
Hi Erik,

Yes you are right - I need to ask my GnuCash questions on the GnuCash forum.

But I'm still confused by the source. The issue I was trying to understand
was that when I use F::Q in a simple perl script (see below), it *works*. I
get the latest ASX.NAB stock price. So what is the default source that F::Q
is using?

Surely it can't be alphavantage as posts on the GnuCash forum suggest that
using alphavantage requires installing a key, which I have not done...

#!/usr/bin/perl
use Finance::Quote;
my $q = Finance::Quote->new();
my %data = $q->fetch('ASX', 'NAB');
print "NAB price is " . $data{'NAB', 'price'} . "\n";

If I understood what the source is that F::Q uses in this script, then
maybe I could configure GnuCash to use the same, and then I'll be golden...


Cheers,
Justin.

**Comment by ecocode** [comment]
jusmop <notifications@github.com> writes:

> Hi Erik,
>
> Yes you are right - I need to ask my GnuCash questions on the GnuCash forum.
>
> But I'm still confused by the source. The issue I was trying to understand
> was that when I use F::Q in a simple perl script (see below), it *works*. I
> get the latest ASX.NAB stock price. So what is the default source that F::Q
> is using?
>
> Surely it can't be alphavantage as posts on the GnuCash forum suggest that
> using alphavantage requires installing a key, which I have not done...
>
> #!/usr/bin/perl
> use Finance::Quote;
> my $q = Finance::Quote->new();
> my %data = $q->fetch('ASX', 'NAB');
> print "NAB price is " . $data{'NAB', 'price'} . "\n";
>
> If I understood what the source is that F::Q uses in this script, then
> maybe I could configure GnuCash to use the same, and then I'll be golden...

The first argument to fetch() is the method which F::Q will exclusively
use.  But, different packages can provide the same method.  So F::Q will
scan those packages and ask for the specific quote till it gets a valid
answer returned.

In your case, 'ASX' is only supported by the module ASX.  However, for
gnucash to use the quote, it requires to return a date which the ASX
module doesn't seem to provide for NAB.  I filed an issue on github for
this.

  ~/DEVELOPMENT/finance-quote >>> perl Examples/stockdump.pl ASX NAB
  $VAR1 = {
            'NABlow' => '30.380',
            'NABp_change' => '0.000
  					 ',
            'NABbid' => '30.410',
            'NABopen' => '30.500',
            'NABprice' => '30.440',
            'NABsuccess' => 1,
            'NABlast' => '30.440',
            'NABhigh' => '30.550',
            'NABvolume' => '5508357',
            'NABnet' => '$0.000
  					 ',
            'NABsymbol' => 'NAB',
            'NABmethod' => 'asx',
            'NABcurrency' => 'AUD',
            'NABoffer' => '30.450',
            'NABexchange' => 'Australian Stock Exchange'
          };

Therefor your best bet for now is to use the new alphavantage method as below.

  ~/DEVELOPMENT/finance-quote >>> perl Examples/stockdump.pl alphavantage NAB.AX
  $VAR1 = {
            'NAB.AXcurrency' => 'AUD',
            'NAB.AXopen' => '30.5000',
            'NAB.AXclose' => '30.4400',
            'NAB.AXdate' => '11/09/2017',
            'NAB.AXvolume' => '5508357',
            'NAB.AXlast' => '30.4400',
            'NAB.AXlow' => '30.3800',
            'NAB.AXsuccess' => 1,
            'NAB.AXhigh' => '30.5500',
            'NAB.AXsymbol' => 'NAB.AX',
            'NAB.AXisodate' => '2017-11-09',
            'NAB.AXmethod' => 'alphavantage',
            'NAB.AXcurrency_set_by_fq' => 1
          };

best
--
erik colson
