### ISSUE TITLE
Currency is missing for stocks from Moscow Stock Exchange from AlphaVantage

### ISSUE THREAD

**Issue by perk11** [finance-quote/finance-quote#64]
Trying to query some stocks from Moscow Stock Exchange, and I get 
```
gnc-fq-dump alphavantage RUAL.ME 
Finance::Quote fields Gnucash uses:
    symbol: RUAL.ME              <=== required
      date: 11/10/2017           <=== required
  currency: ** missing **        <=== required
      last: 40.7500              <=\       
       nav:                      <=== one of these
     price:                      <=/        
  timezone:                      <=== optional

** This stock quote cannot be used by gnucash!!

```

The currency for all Moscow Stock Exchange stocks (that end with `.ME` suffix) should be `RUB` (Russian Ruble).

**Comment by ecocode** [comment]
Konstantin Pereiaslov <notifications@github.com> writes:

> The currency for all Moscow Stock Exchange stocks (that end with `.ME` suffix) should be `RUB` (Russian Ruble).

Thanks.  This will be available in v1.48.

best
--
erik colson
