### ISSUE TITLE
Add Fixer currency rates provider

### ISSUE THREAD

**Issue by MisterY** [finance-quote/finance-quote#65]
Fixer uses ECB's official exchange rates and provides a convenient API.
Could be handy now that Yahoo is off the table.

I've used clients for Python. Perhaps there is already something written in Perl, as well. 

The drawback is that there are only rates for about 32 currencies available.

**Comment by vincentl** [comment]
Added support for multiple currency backends in merge 6e814cc0730eb0979d6dbb944fbf711869d1cf50, include Fixer.io.
