### ISSUE TITLE
Yahoo stopped working for good

### ISSUE THREAD

**Issue by ArturKlauser** [finance-quote/finance-quote#66]
It appears that Yahoo has shut down its quote service entirely. When you access the URL you now get:

> It has come to our attention that this service is being used in violation of the Yahoo Terms of Service. As such, the service is being discontinued. For all future markets and equities data research, please refer to finance.yahoo.com.

And there is a [forum thread](https://yahoo.uservoice.com/forums/382977-finance/suggestions/32103877-http-download-finance-yahoo-com-d-quotes-csv-s-a) confirming the decision to shut it down.

**Comment by ecocode** [comment]
This has been discussed on multiple mailing lists.  yahoo_json has been adapted to a working URL.  Alternative is to use alphavantage.

best
