### ISSUE TITLE
Wrong column for currency in Deka.pm

### ISSUE THREAD

**Issue by sehucke** [finance-quote/finance-quote#72]
The current fondspreise.csv from deka.de has following columns: ISIN; Fondsname; Abrechnungsdatum; Datum_Vortag; Ruecknahmepreis; Ruecknahmepreis_VT; Ausgabepreis; ADDI; Waehrung

Therefore, the column used to obtain the currency in https://github.com/finance-quote/finance-quote/blob/master/lib/Finance/Quote/Deka.pm is wrong. It has to be changed from 12 to 8.

**Comment by sehucke** [comment]
PR exists: #71

**Comment by Andre-J** [comment]
See also https://rt.cpan.org/Public/Bug/Display.html?id=107442 with my patch.

**Comment by vincentl** [comment]
Merged pull request #71.
