### ISSUE TITLE
Currency lookup is broken

### ISSUE THREAD

**Issue by DanJohnsonCERN** [finance-quote/finance-quote#73]
Thanks for the work.

I'm having problems with currency look-up. Three trivial steps to reproduce below:
> git clone https://github.com/finance-quote/finance-quote.git
> cd finance-quote/Examples
> ./currency-lookup.pl USD AUD
Urgh!  Nothing back

**Comment by DanJohnsonCERN** [comment]
OK, this works if I first:
> go to https://www.alphavantage.co/documentation/ and get a lifetime key
> export ALPHAVANTAGE_API_KEY="XXX"
> ./currency-lookup.pl USD AUD
> USD->AUD = 1.2804

Can we document this?

**Comment by bpschuck** [comment]
This is documented in the GnuCash Wiki - [Why doesn't online quoting work](https://wiki.gnucash.org/wiki/FAQ#Q:_Why_doesn.27t_online_quoting_work.3F).

**Comment by bpschuck** [comment]
Closing issue, the requested documentation exists in the GnuCash Wiki - [Why doesn't online quoting work](https://wiki.gnucash.org/wiki/FAQ#Q:_Why_doesn.27t_online_quoting_work.3F)
