### ISSUE TITLE
AlphaVantage now supports batch quotes

### ISSUE THREAD

**Issue by atmattpatt** [finance-quote/finance-quote#77]
On Dec 28, AlphaVantage announced support for fetching quotes in batch. The returned data isn't as rich as the daily time series data, but it is significantly faster.

Example batch quote return value:
```json
{
    "Meta Data": {
        "1. Information": "Batch Stock Market Quotes",
        "2. Notes": "IEX Real-Time Price provided for free by IEX (https://iextrading.com/developer/).",
        "3. Time Zone": "US/Eastern"
    },
    "Stock Quotes": [
        {
            "1. symbol": "PPG",
            "2. price": "118.4100",
            "3. volume": "3734030",
            "4. timestamp": "2018-01-18 16:00:00"
        }
    ]
}
```

I think the main difference is that you only get a single `price` instead of `open`/`close`/`high`/`low`.

The speed increase is pretty significant though. Some benchmarking I did tonight shows it may be 29.6x faster for 25 symbols, 96.3x faster for 250 symbols. This is just from one run, but anecdotally the results were pretty consistent across multiple runs.

```
./benchmark.rb
Using 25 symbols: [list omitted for brevity]

Rehearsal ------------------------------------------------------------
Multiple single requests   0.090000   0.040000   0.130000 ( 29.845046)
Batch requests             0.000000   0.000000   0.000000 (  0.382820)
--------------------------------------------------- total: 0.130000sec

                               user     system      total        real
Multiple single requests   0.080000   0.040000   0.120000 ( 22.843711)
Batch requests             0.000000   0.010000   0.010000 (  0.772521)

Total number of requests executed (including rehearsal):
Single - 50
Batch  - 2

./benchmark.rb 250
Using 250 symbols: [list omitted for brevity]

Rehearsal ------------------------------------------------------------
Multiple single requests   0.890000   0.350000   1.240000 (237.607558)
Batch requests             0.010000   0.000000   0.010000 (  0.575303)
--------------------------------------------------- total: 1.250000sec

                               user     system      total        real
Multiple single requests   0.830000   0.320000   1.150000 (265.849517)
Batch requests             0.010000   0.000000   0.010000 (  2.759761)

Total number of requests executed (including rehearsal):
Single - 500
Batch  - 6
```
(Source is available at https://github.com/atmattpatt/alphavantage-benchmark)

Does it seem worthwhile to switch to batch quotes, or provide batch quotes as an additional source? It seems like the speed up would be pretty helpful for GnuCash users who might have lots of symbols to fetch, but only need the last price.

**Comment by Swatinem** [comment]
Hm, I tried playing around with this, but https://www.alphavantage.co/documentation/#batchquotes says:

> Given the specifications of our data provider (IEX), we currently only offer US stock quotes during US market hours through this API.

So I don’t think its feasible to switch if "the other half of the world" is excluded. Would have been really nice though. The batch API feels really snappy. And I’m getting a lot of errors lately in gnucash after multi-minute freezes. (I guess its a completely different issue to not hang the complete app when fetching quotes)

**Comment by ecocode** [comment]
A valid solution would be to add a new module i.e. Alphavantage_batch.pm

**Comment by atmattpatt** [comment]
If anyone is interested in batch quote support, I added a new Alphavantage_Batch module in https://github.com/finance-quote/finance-quote/pull/95. It does seem to be more reliable when pulling quotes for all my securities in Gnucash than the usual Alphavantage module.

**Comment by ecocode** [comment]
Great !
Do you get stock quotes returned _after_ market hours too ?  Quoted from alphavantage "we currently only offer US stock quotes during US market hours through this API.",  it sounds like this api call won't work after hours...  feedback welcome

**Comment by atmattpatt** [comment]
I was working on it after US market hours, and it was returning data. Perhaps Alphavantage means that the API won't return after-hours trading data?

I can look after markets close today at the data being returned and see if it's just the closing price.

**Comment by alstephan** [comment]
Does AV still have the batch quotes endpoint? What's the base API call for it?

**Comment by atmattpatt** [comment]
@alstephan The URL _was_ `https://www.alphavantage.co/query?function=BATCH_STOCK_QUOTES` but it does indeed look like AlphaVantage has removed this functionality. In light of that, I'm going to close this issue.

**Comment by alstephan** [comment]
@atmattpatt that endpoint still exists e.g. `https://www.alphavantage.co/query?function=BATCH_STOCK_QUOTES&symbols=AAPL,MSFT&api_key=12345` but it seems it only works with US stocks, not global stocks.

**Comment by goodvibes2** [comment]
AlphaVantage batch quotes has always only been for US stocks.

**Comment by alstephan** [comment]
> AlphaVantage batch quotes has always only been for US stocks.

Thanks. That's a shame. Not sure why it's not available for global stocks as well, since individually, global stocks seem to be queryable for real-time data. I've reached out to the AV support team for more info.

**Comment by atmattpatt** [comment]
@alstephan mea culpa! I noticed the documentation was gone but didn't actually test the endpoint. I am curious what AV support says about support for non-US stocks and if they even plan to support batch quotes in the future since they have removed the docs.

**Comment by bpschuck** [comment]
Closing this issue as the API is no longer offered.

    curl 'https://www.alphavantage.co/query?function=BATCH_STOCK_QUOTES&symbols=AAPL,MSFT&api_key=YOURKEYHERE'
    {
        "Error Message": "the parameter apikey is invalid or missing. Please claim your free API key on (https://www.alphavantage.co/support/#api-key). It should take less than 20 seconds, and is free permanently."
    }

**Comment by syuraj** [comment]
![image](https://user-images.githubusercontent.com/503803/129834709-f8349d81-5719-46dc-b2d4-6aac2b3459c7.png)
