### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by MisterY** [finance-quote/finance-quote#81]
Hi,

A couple of us are interested in providing and using a Python version of F::Q for price retrieval for different other projects, including Piecash, Gnucash Portfolio, Asset Allocation. Would you be interested in hosting this project and including myself and @sdementen as maintainers?

This would be a CLI interface on top of a library (API) allowing direct use as well as being called from other apps/scripts.

Cheers

**Comment by sdementen** [comment]
+1

**Comment by sdementen** [comment]
You would see this as a project "finance-quote-python" under the organization "finance-quote"?

**Comment by MisterY** [comment]
Something like that, yes. It would make sense to be under the same umbrella. If you agree, we can try this approach first.

Note to others - we already have working code for fetching prices from a few providers that would be migrated to this project. Others would be free to add their favourite providers.

**Comment by MisterY** [comment]
Link to the repo (just started): https://github.com/MisterY/finance-quote-python
This can be migrated under this project, if accepted.

**Comment by ecocode** [comment]
It doesn't feel right to mix two projects like these.  i.e. package managers would need to add both Perl and Python dependencies even if if the user only wants to use one of the tools..
Also failing tests for one project would prevent installation for the other.
So I guess it is preferable to separate this projects.

**Comment by ecocode** [comment]
closed due to no reactions
