### ISSUE TITLE
Better error message for modules which are known not to work anymore

### ISSUE THREAD

**Issue by ecocode** [finance-quote/finance-quote#94]
Modules which are known not to work should report this when used.  Albeit the query should be run because maybe the site or api changed back..
But if it fails, just suggest that the module is known not to work.

**Comment by bpschuck** [comment]
My thought on this would be to remove the module so it can not be used. What do you think @vincentl ?

**Comment by vincentl** [comment]
@bpschuck - I agree, the module should be removed.  Leading up to 1.50, we did remove quite a few modules.  In the process of investigating a failure, we will determine if the source has a new design.  If so, I is pretty unlikely the old module will work again.  In the off chance it does, we can just restore it from version control.

**Comment by bpschuck** [comment]
That being the case, I am closing this issue.
Thanks.
