### ISSUE TITLE
Newbie Install Issue

### ISSUE THREAD

**Issue by drschrank** [finance-quote/finance-quote#96]
Documentation refers to an INSTALL file for more information on installation protocol. Does not appear to be present in distribution. Installation instructions on cpan page do not  download dependencies, in particular Mozilla::CA, and it is unclear how to do this.

**Comment by Nurdok** [comment]
Ping, how do I install this?

**Comment by pkryger** [comment]
@Nurdok Not sure if this is the correct, recommend, or for that matter, the best way to install this source code, but I did this:

```bash
cpan install Dist::Zilla
cd finance-quote
dzil build
cd Finance-Quote-1.48
cpan .
```

I agree, that docs would need an update. If someone can confirm this is the correct way I can cut a PR.

**Comment by bpschuck** [comment]
Assuming you have Perl installed (outside the scope of this question):

`cpan install Finance::Quote`

or

`perl -MCPAN -e shell
install Finance::Quote`

You would only need to use method described by Mr. Kryger if you needed a recent fix not yet available through CPAN.

**Comment by bpschuck** [comment]
@pkryger - Dist::Zilla is used by module authors and contributors to prepare packages for uploading to CPAN. It is not meant as a tool for general Perl users to install modules. Thank you.

**Comment by pkryger** [comment]
@bpschuck I do agree that it's a way better to install the module via CPAN for most of users. I might have miss interpreted the question, as I was trying to fiddle with this project myself a couple a weeks ago. Knowing a bit or two about programming, I consider myself a _newbie_ in this project, and I was struggling to install the tinkered version following the [Installation section](../tree/master/README.md#INSTALLATION). From your last comment, I recon the `Dist:Zilla` approach I described is a good way for someone who is trying to test a new feature. If so shouldn't the [Installation sectoin](../tree/master/README.md#INSTALLATION) be updated?

**Comment by vincentl** [comment]
I was working on some terse documentation to help people get started from cloning the git repo and using dzil.  I pushed a dev branch that moves DEV-RELEASE-INFO.org or developer-info.txt and adds a getting started section.

**Comment by bpschuck** [comment]
Good info there. But maybe incorporate it into Documentation/Hackers-Guide? Looking the CPAN release, I'm assuming the tag would be changed to reflect the current version? Also in the CPAN section, shouldn't the clone be of finance-quote/finance-quote.git and not pjf/finance-quote.git? If you access pjf/finance-quote.git, you get redirected to finance-quote/finance-quote.git. Lastly, the last version uploaded to SourceForge is 1.42, and you need to have permission to upload.

**Comment by vincentl** [comment]
Good point, see commit f463f30.  I moved the CPAN information into Documentation/Release.txt on dev, but I didn't touch the content because I've never done a release.  

I incorporated the how-to-dzil into the Hackers-Guide.  I updated the later sections to reference github.  This should definitely be reviewed by a second set of eyes.

I assume sourceforge is still right for the mailing list.

**Comment by vincentl** [comment]
Updated Documentation/Hackers-Guide was merged into master, which covers the original issue.
