### ISSUE TITLE
Alphavantage throttling

### ISSUE THREAD

**Issue by knappster1** [finance-quote/finance-quote#97]
Since yahoo disabled the API, using finance::quote has become more burdensome for users.  I have been using alphavantage for finance::quote amongst other things.  It seems a few weeks ago they further throttled API queries so that it is causing issues when using finance::quote for more than 8 queries in sequence.  I am currently using it with gnucash and I have switched from alphavantage with some items I developed in php due to this issue.  I noticed that alphavantage was using IEX trading as their source, so I started using them directly.  They do not require a key and claim as many as 100 queries per minute.  Is there a possibility of adding this as a source to finance::quote?

**Comment by doctaweeks** [comment]
Install Finance-Quote-IEX and set the environment variable FQ_LOAD_QUOTELET="-defaults IEX". You'll find it in the "unknown" type if you're using GnuCash.

**Comment by knappster1** [comment]
@doctaweeks I just installed Finance-Quote-IEX with cpan
`cpanm Finance::Quote:IEX`
Then I setup the FQ_LOAD_QUOTELET as a windows user Environment Variable
In the "unknown" type I was able to select "iex" and now it appears to be working great.  Thanks!
