### ISSUE TITLE
AlphaVantage always returns an error when calling require_labels()

### ISSUE THREAD

**Issue by jcp-sd** [finance-quote/finance-quote#98]
I discovered that if one calls `require_labels()`, then any subsequent fetch always returns an error. The argument of `require_labels()` doesn't really seem to matter. If you require _anything whatsoever_, a fetch will always return an error.

The fix turned out to be pretty simple, as the `labels()` method in `AlphaVantage.pm` is erroneously shadowed. Here is my fix for the labels method below inline, or apply the attached unified diff using patch. It worked just fine for me.

```
sub methods {
    return ( alphavantage => \&alphavantage,
             canada       => \&alphavantage,
             usa          => \&alphavantage,
             nyse         => \&alphavantage,
             nasdaq       => \&alphavantage,
             vanguard     => \&alphavantage,
    );
}

sub labels {
    return ( alphavantage => [qw/date isodate open high low close volume last/]
    );
}
```

[PATCH-labels.txt](https://github.com/finance-quote/finance-quote/files/2343645/PATCH-labels.txt)

**Comment by ecocode** [comment]
Thanks
This was a bug and is solved today
