### ISSUE TITLE
Yahoo JSON quotes for UK stocks wrong denomination

### ISSUE THREAD

**Issue by achampion** [finance-quote/finance-quote#99]
YAHOO JSON is not converting UK stocks properly to GBP, the values are being return in GBX (GBp) pennies, so the results are off by a factor of 100.

**Comment by pwusher** [comment]
This is actually a showstopper to using Finance:Quote in Gnucash as investment assets are showing at 100 times the correct value. It seems that a SCALE_FIELD function needs to be incorporated somehow but I have no idea how to do this. Can anyone help with instructions or a workaround (other than artificially dividing a shareholding by 100)?

**Comment by pwusher** [comment]
I hope I am not breaking Github protocol by posting a layman's solution to this problem. There is a patch suggested by iamamoose (pull request #70) which has not yet found its way into the latest Finance:Quote. With thanks to him, here is what worked for me as a non-coder.

Search for the file YahooJSON.pm in the directory used by Finance:Quote. In Ubuntu the full path is /usr/share/perl5/Finance/Quote/YahooJSON.pm. Note that there may be several files with the same name elsewhere so you may need a bit of trial and error. Once you have found the right one you might want to back it up before changing it.

Open an editor as root (or administrator) and find line around 128 which is [  $info{ $stocks, "volume" }   = $json_volume;. ]

After that line paste in the following:

                # The Yahoo JSON interface returns London prices in GBp (pence) instead of GBP (pounds)
                # and the Yahoo Base had a hack to convert them to GBP.  In theory all the callers
                # would correctly handle GBp as not the same as GBP, but they don't, and since
                # we had the hack before, let's add it back now.
                #
                # Convert GBp or GBX to GBP (divide price by 100).
                if ( ($info{$stocks,"currency"} eq "GBp") ||
                     ($info{$stocks,"currency"} eq "GBX")) {
                    $info{$stocks,"last"}=$info{$stocks,"last"}/100;
                    $info{ $stocks, "currency"} = "GBP";
                }

Save the file and enjoy a correct valuation next time you update prices.

**Comment by ecocode** [comment]
PR 70 is merged
